### ISSUE TITLE
Project name as title

### ISSUE THREAD

**Issue by m1ga** [danielbrodin/atom-project-manager#10]
Would it be an option to set the project name as a title for the current atom editor?

**Comment by tinchoz49** [comment]
this is a great idea! :+1:

**Comment by guiraldelli** [comment]
@m1ga, I think it is already implemented and I suppose this issue can be closed, no?

![project-switch](https://cloud.githubusercontent.com/assets/530790/9787252/6a275d2a-57c1-11e5-9cc3-e1ac0fb342ab.PNG)

**Comment by m1ga** [comment]
I was talking about the editor window title:
![s](https://cloud.githubusercontent.com/assets/4334997/9787787/cd2f267e-57c5-11e5-8ede-ac64a58fb499.png)

so that you can spot the project it in the taskbar easier. 
But like @eigilsagafos said it would be great to use "custom title" and connect it to the project manager

**Comment by danielbrodin** [comment]
I have added a service/API to the package now so if the custom-title package implements it, it would have access to the current projects title :)

**Comment by danielbrodin** [comment]
I have done a PR to the custom-title package now https://github.com/postcasio/custom-title/pull/10

**Comment by m1ga** [comment]
:+1: awesome, thank you

**Comment by yufanyufan** [comment]
Since custom title is not accepting PR, can we add the function to this package directly?
