### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by pastuxso** [danielbrodin/atom-project-manager#103]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `project-manager` package
```
Package.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app/src/package.js:430:9)
Package.getStylesheetPaths (/Applications/Atom.app/Contents/Resources/app/src/package.js:441:32)
```

**Comment by danielbrodin** [comment]
Say what? The less files are already stored in a [styles](https://github.com/danielbrodin/atom-project-manager/tree/master/styles) folder in the package.

Or do you mean something else?
