### ISSUE TITLE
Switching Project with folder names that contain spaces doesn't work.

### ISSUE THREAD

**Issue by changalberto** [danielbrodin/atom-project-manager#104]
Stopped working with Atom 0.192.0

**Comment by danielbrodin** [comment]
What environment are you using? On my mac with Yosemite it works fine.

**Comment by changalberto** [comment]
I'm in Yosemite as well, but please disregard for now. This might've been a conflict with another package: ``save-session`` in Atom 0.192.0. But this package has now been deprecated, since it is now a core support in Atom 0.193.0.

**Comment by danielbrodin** [comment]
Ok :)
