### ISSUE TITLE
Selecting a file opens new copy of the file even if it's open in another pane. 

### ISSUE THREAD

**Issue by asleepinglion** [danielbrodin/atom-project-manager#105]
When using multiple panes to organize open files, clicking on a file from the project manager should open the file if it's not already open. This works fine when only using one pane, or when the cursor is in the pane actively being used, but when the file is in another pane, it just opens another copy of the file. :(

**Comment by danielbrodin** [comment]
This is not part of the Project Manager but Atom so will close this.
