### ISSUE TITLE
Switching away from a project that has a setting does not revert the setting

### ISSUE THREAD

**Issue by nickmccurdy** [danielbrodin/atom-project-manager#107]
I am currently mainly using this package's project settings feature for configuring code style differences for specific repositories. I would like to leave my global Atom settings at my personal preference and make exceptions with the settings feature for specific projects, but it seems like I would need to copy my preferred settings to every project except the projects that are exceptions.
## Steps to reproduce
1. Make sure you have at least two projects.
2. Edit the first project's settings and set a field that is not set on the second project. For example, set a different number of tabs or spaces for indentation for the first project only.
3. Open the first project.
4. Switch to the second project and observe Atom's behavior or look at Atom's settings to confirm what the setting value is.
## Expected results

The setting's value reverts back to what I had before. For example, if I ask Atom to indent with two spaces, then switch to a project with tab indents, and then switch to another project that doesn't define this setting, I should be back on indentation using two spaces.
## Actual results

The setting's value stays with the value from the first project.

**Comment by dangerousdan** [comment]
Same issue here. 
This causes issues if you disable packages for certain projects. Eg. 
``` 
project1:
  path: "path1"
project2: 
  path: "path2"
  settings:
    core:
      disabledPackages: [
        "example-package"
      ]
```
There is no `core.enabledPackages` setting, so there seems to be no possible way for a disabled package to be re-enabled when switching back to package 1

**Comment by nicolasmccurdy** [comment]
@dangerousdan Your example would be fixed if you emptied `disabledPackages` as needed, right?

**Comment by Fire-Dragon-DoL** [comment]
Same issue for me, I have in my project:

```cson
  settings:
    core:
      ignoredNames: [
        "compiled"
        "node_modules"
        ".sass-cache"
      ]
```

Although in my other project I have a folder named `compiled` which I want be able to see/access/search in, but settings.cson is not restored after changing project, so I end up with having to store the entire settings in each project

**Comment by dangerousdan** [comment]
@nicolasmccurdy I assume you mean to set `core.disabledPackages` to an empty array for Project 1 in my example above? If so, then issue still remains. Changing projects enables/disables options as expected *only* when the project I am switching to isn't already open

**Comment by guiraldelli** [comment]
Is switching projects working at all for you, guys? It doesn't even work for me! :disappointed:

**Comment by danielbrodin** [comment]
I have not experienced this, but does this still happen after 2.0? The way the settings is added have been changed a bit.

**Comment by guiraldelli** [comment]
@danielbrodin Answering you questions, I found a problem in my `projects.cson` and fixed it. I am sorry for the comment: it is working just fine! :sweat_smile:

**Comment by guiraldelli** [comment]
Anyhow, I tried to reproduce the steps @nicolasmccurdy suggested but I just couldn't: everything works fine, now.

For the sake of information, I am using Atom 1.0.11 and project-manager 2.5.1.

Hence, I think the problem does not exist anymore and the issue could be closed. :grinning:

**Comment by Fire-Dragon-DoL** [comment]
@guiraldelli I'll be testing in a minute

**Comment by dangerousdan** [comment]
This is still an issue for me when disabling packages per project. On Atom 1.0.11 and project-manager 2.5.1

Using the minimap package as an example:
```
p1:
  title: "p1"
  paths: [
    "/home/dangerous/repos/p1"
  ]
  settings:
    core:
      disabledPackages: [
      ]
p2:
  title: "p2"
  paths: [
    "/home/dangerous/repos/p2"
  ]
  settings:
    core:
      disabledPackages: [
        "minimap"
      ]
```
Switching from `p1` to `p2` disables the package. 
When switching back to `p1` the package is still disabled.

**Comment by guiraldelli** [comment]
@dangerousdan Can you verify if it isn't related with the issue #146?

**Comment by dangerousdan** [comment]
@guiraldelli it is in fact as described in #146

**Comment by danielbrodin** [comment]
I have tried to disable the minimap package for one of my projects, and it keeps being disabled for just that project. Have you perhaps opened the settings view and changed something there? That will trigger a save and save all the current settings.

**Comment by dangerousdan** [comment]
So far I've been confirming the behaviour by checking in the settings view and searching for that package.
I've just retested without opening the settings view and the behaviour is as expected :+1:

**Comment by joergmoldenhauer** [comment]
I have a similar problem. When I open a project which has settings, the settings are not applied. When I open the projects.cson and save it, the settings are applied.

Here is my code of this project in the projects.cson.
````
{
    title: "My Project"
    paths: [
      "C:\\repositories\\my-project"
    ]
    settings:
      whitespace:
        ensureSingleTrailingNewline: false
        removeTrailingWhitespace: false
  }
````

Expected result: When I open the project whitespaces should not be removed on save.
Actual result: Whitespaces are removed on save (as defined in my default atom settings). Only after opening projects.cson and saving it whitespaces are kept.
