### ISSUE TITLE
Project Tree Erased

### ISSUE THREAD

**Issue by cakenggt** [danielbrodin/atom-project-manager#111]
When I right click on a file on my computer and select "Open with Atom", any projects I had in the project tree before are not there anymore.

This does not happen if I have atom already open. The project tree is only erased if Atom is not already open when I select "Open with Atom".

I am running Windows 7 and have Atom v0.204.0 and Project Manager v1.15.7 (latest as of today).

**Comment by danielbrodin** [comment]
This is a bug with Atom and there is an issue up for it
