### ISSUE TITLE
Just show folders when a project is opened

### ISSUE THREAD

**Issue by TreyTaylor** [danielbrodin/atom-project-manager#114]
Hey :-)

Only a request, not an issue.

Is there a way to display just the project folders instead of all of its subfolders and its files?

e.g. instead of

Project Folder
   SubFolder1
   SubFolder2
Project Folder
   File.php

have:

ProjectFolder
ProjectFolder

?

Thanks :smile:

**Comment by adambuczynski** [comment]
I think this already works like that. Unless it remembers what you had open last time for that same project?

**Comment by TreyTaylor** [comment]
sorry, my question wasn't too clear, what I mean is, if I switch projects or open one, it will show anyything and everything where as I just want to see the project folders instead of all of their contents at once :-)

**Comment by adambuczynski** [comment]
Yes, I understood that :)

When I open a project, it shows the closed project folders, not all of their contents at once. However, when I open a project that was open before, it opens the folders that were already open.

If I then manually close the folders, close the project, and then re-open the project, the folders will remain closed.

**Comment by adambuczynski** [comment]
Maybe this is what you're referring to: https://github.com/atom/atom/issues/6605

**Comment by TreyTaylor** [comment]
Weird.. for me it shows everything :l 
what OS cha use?

**Comment by adambuczynski** [comment]
This is on Mac OS X.

**Comment by TreyTaylor** [comment]
Ah, I'm on Windows 7.. maybe it's a slight difference in the code for your OS?

**Comment by danielbrodin** [comment]
I have the same behavior like @adambuczynski, and if it doesn't work I think it's more a bug with the tree-view package and it should be fixed there, so closing this issue.
