### ISSUE TITLE
Is it possible to open a project without Atom windows?

### ISSUE THREAD

**Issue by adambuczynski** [danielbrodin/atom-project-manager#117]
Currently, pressing the shortcut to open a new project when all Atom windows are closed doesn't work. Is there a way around that, or am I forced to first open a new window, and then open the project?

**Comment by danielbrodin** [comment]
Everything in Atom is rendered in the editor so it's unfortunetly not possible

**Comment by adambuczynski** [comment]
Ok, I will raise it with Atom, see if they can somehow find a work around, or enable a global key binding which doesn't need a screen.
