### ISSUE TITLE
Quick save new project

### ISSUE THREAD

**Issue by adambuczynski** [danielbrodin/atom-project-manager#118]
Would it be possible to implement a "quick save new project" command for the project manager which automatically adds a new project to the projects.cson file for the currently open path? Perhaps it could prompt for a project name before saving as well.

**Comment by danielbrodin** [comment]
Do you mean like the `Project manager: Save Project` command?

**Comment by adambuczynski** [comment]
Yes! Thank you good sir, don't know how I missed that :)
