### ISSUE TITLE
Switch to project window if already open

### ISSUE THREAD

**Issue by jacwah** [danielbrodin/atom-project-manager#119]
If I have project A open and open project B with Shift-Alt-P a new Atom window opens. Project A is still open in a background window. If I open project A again with the same keybind, a new window opens with project A. Now two windows with project A are open.

I think Project Manager should first check if the project is already open in another window. If it is it should focus that window instead of opening a new one.

**Comment by HBeineke** [comment]
:+1:

**Comment by danielbrodin** [comment]
It's Atom that is handling this and it should do it like you want, at least it does for me on a mac. What do you use?

**Comment by cs278** [comment]
I get this problem occasionally on Linux, I can be in project A and switch to project A and sometimes I get a new window. I've not spotted any sort of pattern to it.

**Comment by jacwah** [comment]
Same for me as for @cs278, I can't reproduce it now, but it was definitely occurring before. I'm running Linux Mint 17 with Cinnamon.

**Comment by misko321** [comment]
Here's what I've noticed:
If you start Atom, it opens the folder that was previously loaded (it just restores your last session). However, *Project Manager* doesn't grasp that the opened folder is one of its projects (so for *Project Manager* the project is still seen as **not** opened). If you then try to load it, *Project Manager* starts a new window (with the same folder loaded), which only then is considered by *Project Manager* as opened. This might match both @jacwah and @cs278 descriptions.
I'm running Ubuntu 14.04, Atom 1.0.5.

**Comment by jacwah** [comment]
I tested it now and I think you're right @misko321. I get the same behavior you describe.

**Comment by danielbrodin** [comment]
Well, the package is using Atoms API to open new projects and it is Atom that is handling which projects are already open and switch between them. There seems to be an issue with Atom and the first project that is opened. The same thing should happen if you use the File -> Open option for opening the same project.

**Comment by misko321** [comment]
It seems that the issue with opening the project's folder again has been fixed as for Atom v1.0.9. Everything works as expected now.

**Comment by danielbrodin** [comment]
Great, seems to work for me too so closing the issue :)
