### ISSUE TITLE
Filter duplicate entries in file menu/switcher

### ISSUE THREAD

**Issue by scherii** [danielbrodin/atom-project-manager#123]
I use the following structure to organize my projects (tree view):

```bash
.
└── theme
	├── sub
	└── index.php

.
└── project
    ├── sub
	├── sub
    │   └── theme
    └── sub
```

It's handy if you mainly work on a theme and occasionally have to edit config files.

To achieve this I included two paths in my project CSON:
```cson
"project":
  paths: [
    "/Users/scherii/Code/project/sub/theme"
    "/Users/scherii/Code/project"
  ]
```
This works great but it creates duplicate entries in the file menu (`⌘-P`).
![Screenshot: ⌘-P](http://i.imgur.com/gZ8DEeD.png)

**Comment by danielbrodin** [comment]
Can see your problem there, but I think it's something that probably should be done in the [fuzzy-finder](/atom/fuzzy-finder) package.
