### ISSUE TITLE
Suggestion : Integrate Eclipse project and Visual Studio project File

### ISSUE THREAD

**Issue by shanalikhan1** [danielbrodin/atom-project-manager#126]
Hi  , 
I have a good suggestion , kindly add a feature where we can open eclipse project file in order to view all the projects in eclipse should be added in this project. and same with visual studio.
There can be 2 possibility to convert eclipse project file and visual studio solution file to your project manager file , it should be binded to your file , when your project file is opened it should check for that latest eclipse or visual studio solution file in order to refresh all the files added in that projects and create your own project file.

**Comment by danielbrodin** [comment]
Hi, I don't use either VS or eclipse which would make it hard for me to implement, but I would welcome a pull request that implements it.
