### ISSUE TITLE
Understand which project is open on startup

### ISSUE THREAD

**Issue by scythargon** [danielbrodin/atom-project-manager#128]
Hello and thank you for your majestic plugin!

The only issue I have noticed is: when you have some project open, close the editor, start in again (it will open with the same project), go to projects list and select the same project - it will open one more Atom window with the same project.

Thank you:)

**Comment by danielbrodin** [comment]
Yeah, Atom seem to have some weird problem with the first project that is opened. This doesn't have anything to do with the Project Manager, it's strictly Atom. Think I have seen an issue up for this, or something like it on the Atom repository, but don't know how it's been going with it.
