### ISSUE TITLE
Option to allow opening of project in multiple windows?

### ISSUE THREAD

**Issue by jesseleite** [danielbrodin/atom-project-manager#131]
If one has multiple monitors, it'd be nice to have an opt-in setting to allow opening of project in multiple windows for display on multiple monitors.  Would this be easy to implement?

**Comment by till-varoquaux** [comment]
I run on a multi-screen setup at work and ideally I would have the option for "Application: new window" to open with the same project.

**Comment by JSn1nj4** [comment]
It would probably be better for Atom itself to allow dragging a file off the main window and creating a new window that open files could also be grouped onto--considering it _is_ based on Chrome. Don't know how much more this feature would slow Atom down though...

**Comment by danielbrodin** [comment]
There is an option (not added to the package yet) that makes Atom not care about any current window and instead always opens up a new window. It's easy to add, but that would make it so that you can't go between projects using the project manager since it would open a new window each time.

**Comment by JesseLeite** [comment]
Yeah would be nice if it were smart enough to know a project window already exists, so switch to that.

**Comment by danielbrodin** [comment]
I have looked at the Atom code some and from what I can tell, a package do not have any way of looking at another window, so currently no way for me to open two windows and then switch between them it seems.

**Comment by andrewhoff** [comment]
This would be a great feature! I also use Atom in a multi monitor setup, and I'd like to be able to have different files of the same project open in multiple windows.

**Comment by ValKiriann** [comment]
Is this thing going to happen? is there a package to make possible the work on multiple monitors with the same project?

**Comment by JSn1nj4** [comment]
This raises a question in my mind: If Atom starts allowing packages to look at multiple windows, how would the package know what window to look at unless Atom also allows the package itself to spawn the new window?

Also, if 1 window of a project is minimized/unminimized, all other "project" windows should be too, right?

So maybe, with whatever other related features come, these new windows should be handled differently anyway. Maybe they shouldn't be exactly like the main Atom window. For example, GIMP's multi-window mode spawns a couple of side panels that can be moved around separate from the canvas window. They don't have the majority of the controls on them that the main window does though, and they minimize with the main window (so they're more like children of the canvas window).

Will see what Atom does I suppose...
