### ISSUE TITLE
After Restart PM still doesn't appear in 'Packages'

### ISSUE THREAD

**Issue by encryptdesigns** [danielbrodin/atom-project-manager#134]
After the update and subsequent restarts of the program Project Manager doesn't appear :(

**Comment by danielbrodin** [comment]
Is it under the install tab or under packages?
If it's installed try opening the console and run `apm uninstall project-manager` and then `apm install project-manager`

**Comment by encryptdesigns** [comment]
I uninstalled Atom for Sublime Text 3 again. But thanks for the comment.
