### ISSUE TITLE
project-manager is not available with all windows closed

### ISSUE THREAD

**Issue by bobrocke** [danielbrodin/atom-project-manager#136]
If all of Atom's windows are closed, project-manager is not available to open an existing project. Could a sub-menu be added somewhere to provide project-manager's commands at any time?

**Comment by danielbrodin** [comment]
I'm afraid not. A window is needed to render the view

**Comment by bobrocke** [comment]
Could project-manager not open a file and then open the project into it? Or are you saying that no menus in Atom can work if there are no open windows?

**Comment by danielbrodin** [comment]
There are menus in Atom that works without a window of course, like File -> New Window, but packages only exist in a window from what I know. The packages menu item is gone without a window too.

**Comment by bobrocke** [comment]
I opened an issue for Atom suggesting menu availability with no open windows: https://github.com/atom/atom/issues/8603

**Comment by bobrocke** [comment]
Would you consider adding a project-manage sub-menu that at least would be available when windows are open to make accessing commands easier/faster?

**Comment by danielbrodin** [comment]
A menu have been added. All commands can be found in the command palette also by typing Project manager

**Comment by bobrocke** [comment]
Thanks! And fast, too. Or was it there all along I was not alert enough to notice?

**Comment by danielbrodin** [comment]
It used to be there but it got removed while rewriting the package and I forgot to add it back since I never use the menu myself but instead access all commands from the command palette :)
