### ISSUE TITLE
project-manager does not remember folder collapsed status

### ISSUE THREAD

**Issue by bobrocke** [danielbrodin/atom-project-manager#138]
When opening a project, it's folders are not open/closed as they were we the project was last closed.

**Comment by danielbrodin** [comment]
This is a bug in Atom when the project is opened in an empty window. So if you open the project in an empty window it will be "broken", then try opening it again and it will open in a new window in the correct state. I think there have been an issue open about this, but I couldn't find it so maybe not.

**Comment by GioLogist** [comment]
By any chance has a fix been implemented for this?
