### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by imp** [danielbrodin/atom-project-manager#143]
[Enter steps to reproduce below:]

1. Open "Edit Projects"
2. Rename project and its title

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.5.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/cyrilp/.atom/packages/project-manager/lib/project.coffee:59

TypeError: Cannot read property '0' of undefined
  at Project.module.exports.Project.isCurrent (/Users/cyrilp/.atom/packages/project-manager/lib/project.coffee:59:32)
  at Project.isCurrent (/Users/cyrilp/.atom/packages/project-manager/lib/project.coffee:1:1)
  at /Users/cyrilp/.atom/packages/project-manager/lib/project.coffee:54:15
  at /Users/cyrilp/.atom/packages/project-manager/lib/db.coffee:43:7
  at /Users/cyrilp/.atom/packages/project-manager/lib/db.coffee:123:9
  at FSReqWrap.cb [as oncomplete] (fs.js:209:19)

```

### Commands

```
 15x -0:43.8.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:41.3.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:21.5.0 project-manager:edit-projects (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:07.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:06.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:05.9.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:05.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "/Users/cyrilp/dev",
    "disabledPackages": [
      "racer",
      "build-tools"
    ]
  },
  "project-manager": {}
}
```

### Installed Packages

```coffee
# User
atomatigit, v1.5.4
autocomplete-python, v0.5.3
build, v0.45.0
language-diff, v0.3.1
language-rust, v0.4.4
linter, v1.5.1
linter-clang, v3.2.1
linter-rust, v0.2.9
minimap, v4.13.3
project-manager, v2.5.0
remote-edit, v1.8.18

# Dev
No dev packages
```

**Comment by adambuczynski** [comment]
I am also getting this error, every time I save the project.cson file:

![ss](https://www.dropbox.com/s/wpc8kqs4r6cew08/Screenshot%202016-01-01%2011.52.24.png?dl=1)

This is with Atom 1.3.2 and project manager 2.6.5 on OS X.

**Comment by danielbrodin** [comment]
Have you manually edited the `projects.cson` and in that case what did you edit? Was it the current project?

**Comment by adambuczynski** [comment]
Yes I edited `projects.cson` manually. I was reordering some of the project paths, possibly the project was open. I tried doing the same now with another project, but couldn't trigger the error.

**Comment by danielbrodin** [comment]
Ok, then some happened during the edit, but good that it works now.

**Comment by adambuczynski** [comment]
Probably a good idea to wrap the code that's causing the error in a check to make sure the index in the array is valid though?

**Comment by adambuczynski** [comment]
Happened again just now. What I did was split one project which had several project folders into individual projects, and then I moved one project up to another position in the file. Saving projects.cson then caused the error. Subsequent saves also triggered the error.

I did not have any of the projects that I modified open at the time.

**Comment by adambuczynski** [comment]
I would like to add that this error also occurs every time I restore my settings (using https://github.com/Hackafe/atom-sync-settings). That package also overwrite the projects.cson, so I assume it's related.

The error occurs independent of what project is open, and didn't use to happen until a few releases ago.

**Comment by AriaFallah** [comment]
I also get this every time that I edit the projects.cson
