### ISSUE TITLE
Unable to access the project list since the last updates

### ISSUE THREAD

**Issue by asitemade4u** [danielbrodin/atom-project-manager#145]
Hi Daniel,
I love Project Manager as I am working concurrently on several projects.
But since two or three updates I cannot have the project list displayed, whatever way I call it [key shortcut or command palette].
Please help because the module is pretty useless otherwise...
Best,
Stephen

**Comment by danielbrodin** [comment]
What version of Atom are you using? Have you tried to uninstall and reinstall the package? Does any error turn up in the notifications or in the console(View->developer->toggle developer tools)?

**Comment by danielbrodin** [comment]
Btw, have you done any manual editing to the `projects.cson` file? If it's not formatted correct, the list will not show

**Comment by mikestopcontinues** [comment]
For the record, I had a similar problem, but no console errors, and reinstall fixed it. Thanks!

**Comment by asitemade4u** [comment]
Hi Daniel,
Sorry not to have responded before.
I use the last version of Atom as I update it automatically. No errors in the console.
Yes I manually modified the cson, here it is:
------------------------------------------------------------------------------------------------------
VTR:
  title: "VTR"
  paths: [
  "/home/stsinc/lampstack-5.4.22-0/apps/vtr/htdocs/wp-content/src/sass"
  ]
ROU:
  title: "ROU"
  paths: [
  "/home/stsinc/lampstack-5.4.22-0/apps/rou/htdocs/wp-content/src/sass"
  ]
SHA:
  title: "SHA"
  paths: [
  "/home/stsinc/lampstack-5.4.22-0/apps/sha/htdocs/wp-content/src/sass"
  ]
WB4:
  title: "WB4"
  paths: [
    "/home/stsinc/lampstack-5.4.22-0/apps/s4u/htdocs/wp-content/src/sass"
    "/home/stsinc/lampstack-5.4.22-0/apps/s4u/htdocs/wp-content/src/twig"
  ]
SEA:
  title: "SEA"
  paths: [
    "/home/stsinc/lampstack-5.4.22-0/apps/sea/htdocs/wp-content/src/sass"
    "/home/stsinc/lampstack-5.4.22-0/apps/sea/htdocs/wp-content/src/twig"
  ]
------------------------------------------------------------------------------------------------------
Do you see anything wrong?I will try the uninstall and will let you know.
Best,
Stephen

**Comment by asitemade4u** [comment]
I reinstalled it > nothing changed.
I deleted the cson and redefined it > works.

Definitely something in my cson.
Best,
Stephen

**Comment by danielbrodin** [comment]
I have added a notification now if `projects.cson` isn't correctly formatted, so should be easier to spot the error now :)
