### ISSUE TITLE
Configurations of projects.cson are getting to config.cson

### ISSUE THREAD

**Issue by guiraldelli** [danielbrodin/atom-project-manager#146]
If I define project-specific configurations in my `projects.cson` file, these are being copied to `config.cson` and, hence, affecting the whole Atom environment.

For example, if my `projects.cson` is something like:

```
myexampleproject:
    title: "My Example Project"
    paths: [
        "C:\\MyExampleProject"
    ]
    settings:
        "tree-view":
            "hideVcsIgnoredFiles": true
            "hideIgnoredNames": true
        core:
            "excludeVcsIgnoredPaths": true
            "ignoredNames": [
                ".cabal-sandbox"
                "dist"
                ".stack-work"
            ]
```

And I hit "Packages → Project Manager → Reload Project Settings" (or simply restart Atom), my `config.cson` has the following lines added:

```
"*":
  "tree-view":
    hideVcsIgnoredFiles: true
    hideIgnoredNames: true
  core:
    ignoredNames: [
      ".git"
      ".hg"
      ".svn"
      ".DS_Store"
      "._*"
      "Thumbs.db"
      ".cabal-sandbox"
      "dist"
      ".stack-work"
    ]
```

This is happening on Atom 1.0.11 and project-manager 2.5.1.

**Comment by guiraldelli** [comment]
Update: it puts the current opened project configuration in `config.cson`, not every project `settings` configurations.

**Comment by danielbrodin** [comment]
I did some testing now, and for me this happens when I change something in the settings view. I guess this is because the package adds settings to the window without saving them, which is what we want, then if something is changed in the settings view, all current settings are saved to the `config.cson`.
Is this how it happens for you as well?

Not sure I can do anything about this

**Comment by guiraldelli** [comment]
You're absolutely right: it is a problem that happens solely when I open the Settings view.

> I did some testing now, and for me this happens when I change something in the settings view.

Actually, it is enough to open the Settings view to copy all the project-only `settings` configurations to `config.cson`.

> [...] then if something is changed in the settings view, all current settings are saved to the config.cson.
> [...]
> Not sure I can do anything about this

It seems to be an Atom issue, not project-manager. Maybe we could report it to the Atom repository?

**Comment by danielbrodin** [comment]
Did some more testing, and it seems to be only the first time you open the settings view that it does the save. But then if you change something at any time in the settings view it does a save to. 

If atom.config.set() is called with option `save` set to `false` it should never save it to the `config.cson`. Should probably be reportet to the Atom repository. I don't have time to do it now, so please do it if you have time :)

**Comment by aexmachina** [comment]
This is happening for me regardless of whether Settings (or config.cson) are open. Furthermore, in trying to isolate the issue the project config is now not being applied at all :(
