### ISSUE TITLE
Config is not applied if project being switched to is already open

### ISSUE THREAD

**Issue by dangerousdan** [danielbrodin/atom-project-manager#147]
When switching from `project1` to `project2`, config only seems to be applied if `project2` is not already open in the background.

On Atom 1.0.11 and project manager 2.51, using the following config:
```
project1:
  title: "project1"
  paths: [
    "/home/dangerous/repos/project1"
  ]
  settings:
    core:
      disabledPackages: [
      ]
project2:
  title: "project2"
  paths: [
    "/home/dangerous/repos/project2"
  ]
  settings:
    core:
      disabledPackages: [
        "minimap"
      ]
```

**Comment by danielbrodin** [comment]
Do you mean that you have project1 and project2 open, 
you have project1 as the active window, 
open the projects.cson file and change a setting for project2, 
then switch window so that project2 is the active one?
And project2 does not have the setting on?

**Comment by dangerousdan** [comment]
I have been confirming my findings by checking in the settings view rather than viewing projects.cson, which as you mentioned in 
https://github.com/danielbrodin/atom-project-manager/issues/146#issuecomment-139281826 is affecting the global config.
So this behaviour seems to just be a by-product of the unexpected settings view behaviour you discovered.
