### ISSUE TITLE
Project location being reset

### ISSUE THREAD

**Issue by dlewand691** [danielbrodin/atom-project-manager#150]
When working in a project, if I edit Atom's .cson file or open another file outside of the project, the projects' original location is being reset to that "outside" file's location. 

Using Atom 1.0.15, Project Manager v2.5.2.

**Comment by danielbrodin** [comment]
I'm not sure what you mean so could you be a bit more clear? Like which `.cson` do you mean, and where do the projects location change?

**Comment by dlewand691** [comment]
Sure. It doesn't seem to do happen regularly, but has happened 3 or 4 times so far which required me to reset the project location url. 

When I'm in a project and then open a file, say, from the desktop and make edits and close it, the tree view on the left updates to that file's location, which means the project location url changed. Today I was tweaking the atom config.cson and it happened. 

I'll try and recreate it and remember my steps to share. Not a deal-breaker, but wanted to share what I've experienced.

**Comment by danielbrodin** [comment]
Sounds really weird and have never happened to me, but this does sound like it has more to do with the Atom core or perhaps the tree-view package than the project-manager, so try open an issue there instead.
