### ISSUE TITLE
Shared CSON file

### ISSUE THREAD

**Issue by ksnyde** [danielbrodin/atom-project-manager#154]
I use project manager on my laptop and desktop and share my atom configuration on dropbox so the `projects.cson` file and up being shared too. This causes a lot of problems and am wondering if there's a way to make each machine have it's own list of repos? Either by having different files or having a different section of the config?

One things that possibly would ease this pain (although it's probably still a "second best" approach) is to recognise when a user adds a file under their user directory and use the "~" alias for the home directory versus a fully qualified directory path as this might mitigate some of the variance between machines.

**Comment by danielbrodin** [comment]
Just set `project-manager.environmentSpecificProjects` to true in your settings and it will create a `projects.[hostname].cson` for each environment :)

**Comment by ksnyde** [comment]
Great! Thanks.
