### ISSUE TITLE
Exclude paths?

### ISSUE THREAD

**Issue by pspeter3** [danielbrodin/atom-project-manager#155]
Is it possible to exclude paths from a project, for example, the build directory?

**Comment by antonkudris-triptop** [comment]
+1. This is an essential feature to exclude catalogs like .git, node_modules etc

**Comment by danielbrodin** [comment]
`tree-view.hideVcsIgnoredFiles: true` will hide the paths ignored from `core.ignoredNames: []`, so it's already part of Atom :)

**Comment by antonkudris-triptop** [comment]
Thanks! That will do the trick.

**Comment by pspeter3** [comment]
This does not seem to work when those files are symlinks themselves.

**Comment by raptor235** [comment]
It would be nice to be able to set this per project not just globally.
