### ISSUE TITLE
Restore settings on focus

### ISSUE THREAD

**Issue by neu-rah** [danielbrodin/atom-project-manager#157]
when using encoding settings:

    settings:
      '*':
        core:
          fileEncoding: "windows1252"

After opening another project (from project manager) that uses a different fileEncoding (on the case a default UTF8) the original project looses encoding definition and starts opening files with the default utf8.

reload-project-settings didn't help either.

all ok on reopening.

**Comment by danielbrodin** [comment]
Do you open the settings view perhaps? Opening the settings view saves the settings globally which will overwrite the setting in all projects. Have not found a solution for this, if this is the cause to the problem?

**Comment by neu-rah** [comment]
yes, its the cause, i was looking on atom api for maybe a solution... it seems that atoms needs a module to switch settings and keep things separated.
https://atom.io/packages/editor-settings ?
Or maybe there's a better way of doing this.
For the moment I will avoid switching back and forth.

**Comment by danielbrodin** [comment]
the editor-settings package only support certain settings which are things that have an API, so nothing I can get from there. I think Atom is building in support for project specific settings so I guess something will come that fixes this, but the only solution right now is to not open the settings view I think.
