### ISSUE TITLE
Perform Project Setup

### ISSUE THREAD

**Issue by Dog** [danielbrodin/atom-project-manager#166]
I would like it if I could tell the project manager to perform certain set up tasks when I select a project. As an example lets say I am creating the front end for an application with an existing server on the back end. I'd like to ensure that I have this back end server running whenever I am working on my project. This means I'd like to open up a terminal window using [terminal-plus](https://github.com/jeremyramin/terminal-plus), and run my server.

Is it possible for me to do this currently?

**Comment by danielbrodin** [comment]
It is not currently possible to trigger other packages, but it's something that could be added. I currently don't have the time to do it myself, but you are welcome to do a PR if you want.

I guess it would work by adding the triggers you want, but not sure how it would work to send data to the package which I guess is what you want?
