### ISSUE TITLE
How to run list projects in init.coffee?

### ISSUE THREAD

**Issue by linaksa** [danielbrodin/atom-project-manager#167]
Hi there, I am new to Atom editor and I really liked project manager plugin. I am looking for a way to run list projects command from init.coffee but does not seem to find a way. Is it possible to auto list the projects when a new windows is open?

**Comment by danielbrodin** [comment]
You could add this code to your `init.coffee``
```
workspaceElement = atom.views.getView(atom.workspace)
atom.commands.dispatch(workspaceElement, 'project-manager:list-projects')
```
This will always show the list view when opening a window. Then you would have to add some logic before it if you only want to show it if there is no project loaded or so.

**Comment by linaksa** [comment]
Awesome, this worked great. Appreciate your help @danielbrodin
