### ISSUE TITLE
Feature request: open project through command line

### ISSUE THREAD

**Issue by qimingweng** [danielbrodin/atom-project-manager#171]
Hi,

I'm not too familiar with Atom's API so this may be impossible, but we can open a folder in atom through the terminal with `atom [directory]`, I wonder if it would be possible to achieve a similar syntax but open these predefined projects instead.

Thanks!

**Comment by lastpotato** [comment]
+1

**Comment by dkerzig** [comment]
Seems like a duplicate of https://github.com/danielbrodin/atom-project-manager/issues/130

**Comment by qimingweng** [comment]
@dkerzig you're right, closing because duplicate of #130
