### ISSUE TITLE
Automatically add projects from folder

### ISSUE THREAD

**Issue by blackjid** [danielbrodin/atom-project-manager#174]
It would be awesome if the projects are automatically added, or proposed based on a `.git` folders search on a path.

Something like this package `https://github.com/prrrnd/atom-git-projects`, but within the project manager package.

**Comment by FezVrasta** [comment]
I would love that too, it's too tricky changing the cson file everytime I want to add a project...

**Comment by danielbrodin** [comment]
> I would love that too, it's too tricky changing the cson file everytime I want to add a project...

You don't have to manually change the file when you want to add a new project. Just open it with Atom and then run `Project Manager: Save project` form the command palette.
