### ISSUE TITLE
Split project files so one can have the project file within the project or at whatever location

### ISSUE THREAD

**Issue by lgomez** [danielbrodin/atom-project-manager#175]
Hello,

This may already be possible but I couldn't find it in the docs nor issues. I'd like to be able to load a project's configuration from another file that, in my case, would likely be a sibling of the paths or somewhere in a client's folder.

``` bash
~
└── Projects
    └── clientA
        ├── project.cson
        ├── repo1
        ├── repo2
        └── repo3
```

That `project.cson`...

``` yaml
title: "My Project"
paths: [
  "/Users/me/Projects/clientA/repo1"
  "/Users/me/Projects/clientA/repo2"
  "/Users/me/Projects/clientA/repo3"
]
```

Then in `~/.atom/projects.cson`...

``` yaml
my_project:
  conf: "/Users/me/Projects/clientA/project.cson"
```

or perhaps...

``` yaml
my_project:
  $ref: "/Users/me/Projects/clientA/project.cson"
```

**Comment by WoodyWoodsta** [comment]
I was thinking about this the other day too. Similar to sublime text where the project config lives in the root of the project.

**Comment by danielbrodin** [comment]
This is something that is on the todo list, but I haven't had time to add it. Not completely sure of how the implementation will look either, but the `conf` option isn't to bad :)
