### ISSUE TITLE
Cannot List Projects

### ISSUE THREAD

**Issue by djallen1289** [danielbrodin/atom-project-manager#182]
When trying to list projects a message will show with title: "Failed to load projects.cson" body: "undefined is not a function". Tried reinstalling. Did not fix issue.

**Comment by MarcelPl** [comment]
"When trying to list projects a message will show with title: "Failed to load projects.cson" body: "undefined is not a function". Tried reinstalling. Did not fix issue. "

Have the same problem.

**Comment by awakekat** [comment]
When I manually delete a listed object in the projects.cson file I get this: "Cannot read property '0' of undefined." I have to delete the entire content of the file, open the path to the project and choose save project again.

**Comment by nyrrad** [comment]
I was having this same issue. I found that updating atom from 1.0.2 to 1.3.3 resolved the issue for me.

**Comment by danielbrodin** [comment]
This should be fixed now
