### ISSUE TITLE
Failed to load projects.cson after 2.7.1 upgrade

### ISSUE THREAD

**Issue by fabio985** [danielbrodin/atom-project-manager#185]
After upgrading Project manager to version 2.7.1, when i go to Project Manager -> List projects i get the error:
Failed to load projects.cson
undefined is not a function

Atom version 1.0.11

**Comment by danielbrodin** [comment]
This is fixed now

**Comment by panteo** [comment]
It's still happening with 2.7.2.

Atom version 1.0.11

**Comment by panteo** [comment]
Fixed with 2.7.3 and Atom version 1.4.0. Thank you very much

**Comment by fabio985** [comment]
+1

**Comment by danielbrodin** [comment]
:)

**Comment by praveenpuglia** [comment]
Happening in 2.7.5. I am on Ubuntu 15.10. Says Failed to load  projects.cson.
`undefined is not a function`

**Comment by danielbrodin** [comment]
@praveenpuglia have you updated to latest Atom? I think you need at least 1.4.0
