### ISSUE TITLE
Open appropriate projects in dev mode

### ISSUE THREAD

**Issue by danielbayley** [danielbrodin/atom-project-manager#191]
If a project’s root (I’m guessing the first path in it’s `projects.cson` array) lives in `ATOM_DEV_RESOURCE_PATH` then the new window that project opens should be in dev mode. Maybe this could be achieved with a simple `dev: true` property in `projects.cson`?

**Comment by danielbrodin** [comment]
Check the read me, there is a `devMode` setting already :)

**Comment by danielbayley** [comment]
@danielbrodin Ah I missed that… neat! :sunglasses:
