### ISSUE TITLE
Comments in projects.cson

### ISSUE THREAD

**Issue by danielbayley** [danielbrodin/atom-project-manager#192]
As it stands I can’t have any comments in the `projects.cson` file because project-manager removes them whenever it writes to it (and also forces 2 space indentation and double quotes…) One of the big advantages of CSON over JSON is comments…

I know Atom also does this with it’s `config.cson`, but surely there’s a way to write to it without reformatting the whole file every time?

**Comment by danielbrodin** [comment]
I'm using the same lib that Atom does for this and as far as I'm aware it does not have support for this. It can read the file with comments, but as soon as it saves it they will be removed since the hole file is replaced with new content.
