### ISSUE TITLE
Fix position i in Packages menu

### ISSUE THREAD

**Issue by larsenwork** [danielbrodin/atom-project-manager#193]
All other items seems to be sorted alphabetically so could be cool if this was too. 

![screen shot 6](https://cloud.githubusercontent.com/assets/3859425/12580991/1913c114-c434-11e5-8b17-5fef1021db01.png)

**Comment by danielbrodin** [comment]
It is for me. Did you just install the package? In that case, try reloading Atom

**Comment by larsenwork** [comment]
![screen shot 8](https://cloud.githubusercontent.com/assets/3859425/12581094/cd26c3e0-c434-11e5-85f7-564ac3d52dd8.png)

Ah, It installing an update. Cheers 👍
