### ISSUE TITLE
per-project settings to be kept in the project root

### ISSUE THREAD

**Issue by Byron** [danielbrodin/atom-project-manager#194]
*Please note that this is not a fully fleshed out, RFC like, feature request, but merely a ping to see if there  is a chance to get it implemented*.

#### Usecase

As a developer, I would like to control settings related to the project, and keep them in the projects revision control system to assure fellow developers have the same settings.
This is relevant for example when configuring atom-linters.

#### Current situation

The developer can store settings per project, which is part of the developers personal settings. Such a file cannot safely be used by other developers.

#### Desired situation

`Project Manager` will look for files within the project root directories that look like project-specific configuration, and make it available to the atom-settings. The last written value wins.

#### Other reference

There is a similar [feature request](https://github.com/atom/atom/issues/5168) for atom.

**What do you think about such a feature ?**. Would you be interested in a contribution ? Do you have any opinion on how the minimum viable implementation could/should look like ?

Thank you 😊

**Comment by danielbrodin** [comment]
Yes, this is something I have been wanting to do for some time, but I just haven't had the time to work on it. Will hopefully get some time free soon though.

**Comment by danielbrodin** [comment]
An update to this can be found here https://github.com/danielbrodin/atom-project-manager/issues/25

**Comment by danielbrodin** [comment]
You can check out #25, but it has now been implemented.
