### ISSUE TITLE
Path is not available

### ISSUE THREAD

**Issue by madsights** [danielbrodin/atom-project-manager#195]
After attempting to save a project with project folders located on my iCloud drive, I'm faced with a "Path is not available" error in my project list. Directory structure looks correct when I Edit Projects…

/Users/Username/Library/Mobile Documents/com~apple~CloudDocs/Development/Projects/new-project

**Comment by danielbrodin** [comment]
Latest release should hopefully solve this.

**Comment by madsights** [comment]
All good. Thanks Daniel, appreciate your work.
