### ISSUE TITLE
Close current project on switching

### ISSUE THREAD

**Issue by darylknight** [danielbrodin/atom-project-manager#197]
Hey Daniel,

Do you think it'd be possible to close the current project when you switch to a new one? I'm used to the "Quick switch project" functionality from sublime and I end up having lots of Atom windows open as it doesn't "switch" project, it just opens a new one.

Cheers!

**Comment by danielbrodin** [comment]
Enabling the `Close Current` setting will do this :)

**Comment by darylknight** [comment]
Oh! Thanks, I'd looked in the dropdown menu but hadn't remembered to look in package settings. Great :)
