### ISSUE TITLE
Feature Request: Save Code Folding

### ISSUE THREAD

**Issue by optikalefx** [danielbrodin/atom-project-manager#198]
It's been months on this ticket https://discuss.atom.io/t/save-code-folding/17793/4
I'm wondering if this is something this plugin can solve. Save the state of code folding with a project?  I can probably build this as a PR maybe but I haven't dealt with ATOM before so maybe if you run off the top of your head how you would do this that would save me hours of unknown research.

Thanks!

**Comment by danielbrodin** [comment]
The project manager in it's current state doesn't have anything in it that would help with implementing this and I can't really think of a way to do this.

There is an issue up on the Atom repository for this https://github.com/atom/atom/issues/8764, but not much action there either though :(

**Comment by optikalefx** [comment]
@danielbrodin Don't you have a place to save the state of the project? What tabs were open, etc. I was thinking that would be a good place to save the state of the folded coded in those files. At first in the open tabs and then of course in closed files through the life of editing that project.

**Comment by danielbrodin** [comment]
That was something that was going to be added because of keeping track of open tabs etc... but that was implemented directly in Atom so there have been no need to save the projects state. I'm all up for adding such a thing though if someone implements it.

**Comment by optikalefx** [comment]
@mehcode so nice. Beautiful. Thank you!
