### ISSUE TITLE
Per-project stylesheet settings

### ISSUE THREAD

**Issue by zamb3zi** [danielbrodin/atom-project-manager#199]
Is it possible to configure `styles.less` on a per-project basis? To start with, I would just like to modify the background color so I can easily distinguish my various open projects. Thanks for a great package.

**Comment by danielbrodin** [comment]
Could be an interesting feature. If anyone finds out a way to do it a PR would be nice.

**Comment by RenaKunisaki** [comment]
There must be a way to load your own stylesheet and override `styles.less`? Put such a stylesheet in the project directory alongside project.cson, and there you go.
