### ISSUE TITLE
Failed to load projects.cson (undefined is not a function)

### ISSUE THREAD

**Issue by quamenzullo** [danielbrodin/atom-project-manager#201]
The project-manager seems to have some trouble: when I opened up an existing project, it couldn't load the tabs and displayed this "Failed to load projects.cson" and "undefined is not a function".

I see it seems close to #159.

I also have a symbol-tree view plugin. Disabling it didn't solve the case, I still get the error (at startup, now...).

But I don't know what I should do with a coffee linter. Also, my projects.cson file is still accessible (even using Project Manager > Edit Projects) and is quite simple:

```
mathmaker:
  title: "mathmaker"
  paths: [
    "/home/nico/dev/mathmaker/mathmaker/"
  ]
pilberry:
  title: "pilberry"
  paths: [
    "/home/nico/dev/pilberry/pilberry"
  ]
nothing:
  title: "nothing"
  paths: [
    "/home/nico/dev/"
  ]
```

**Comment by danielbrodin** [comment]
Which version of Atom do you use? There is a function that is being used that came in a newer version of Atom.

**Comment by quamenzullo** [comment]
Ok, I see the last version is 1.5.4 and mine is 1.0.11. I think I updated project-manager recently and this might have caused the problem. I try to update it (if the dependencies of my distribution are met).

**Comment by quamenzullo** [comment]
Indeed the update solved the problem. Sorry about that and thanks for your quick reply :)

**Comment by danielbrodin** [comment]
No problem :)
