### ISSUE TITLE
Header Feature

### ISSUE THREAD

**Issue by HunSpeedi** [danielbrodin/atom-project-manager#204]
Hi, i would like to ask:
Can you add a feature where the window header show the actual project name?
e.g.
index.js--D:\Projects\todoapp--Atom 
change
[Projectname] 
or
 [Projectname] index.js--D:\Projects\todoapp--Atom

Sincerely: Lóránd Véger

**Comment by danielbrodin** [comment]
This feature would be available with the Custom title package, but the author have not added my PR for that yet. https://github.com/postcasio/custom-title/pull/10
