### ISSUE TITLE
"Swap Projects" not "Open New Project"

### ISSUE THREAD

**Issue by OwenMelbz** [danielbrodin/atom-project-manager#205]
More and More commonly I'm finding myself toggling between projects, I'm trying out Atom compared to using Sublime.

One of my biggest gripes so far is the performance, and wondering what you guys could suggest if this is possible with project-manager.

In Sublime when you do quick project swap its instant.
In Atom when you swap project it takes a couple of seconds (this might be due to the fact project-manager creates a new window instance)

You can see the performance difference in this little video

https://drive.google.com/a/selesti.com/file/d/0Bxqca2RsGkfTRjE0ci1heGtnaGM/view

Is there anyway to make project-manager simply swap projects, rather than opening whole new ones?

Thanks

**Comment by danielbrodin** [comment]
Thanks to @mehcode this is something that I'm working on right now actually. I have a lot going on right now though so I haven't had time to finish it, but will hopefully be done soon.

**Comment by OwenMelbz** [comment]
Ah that's handy, out of curiosity what do you class as "soon" :p months? Or days.

Manu thanks for the efforts though!

**Comment by mehcode** [comment]
@OwenMelbz There is an implementation of "Swap Projects" in https://github.com/mehcode/atom-project-plus. It started out as a PR to this project but I decided to fork it as I grew to not like manually saving projects (and instead let atom tell me the projects you have).

**Comment by OwenMelbz** [comment]
Hmm okay, will be interesting to give this a look! 

Thanks both of you for the information, much appreciated :)

P.s. Any tips to increase atoms performance more than welcome :p
