### ISSUE TITLE
Failed to load projects.cson

### ISSUE THREAD

**Issue by pehota** [danielbrodin/atom-project-manager#209]
Hi,
Kudos on the awesome work you have done! :+1: :smiley: 

Today the project manager crashed showing the error from [issue 207](https://github.com/danielbrodin/atom-project-manager/issues/207).
I restarted Atom but then all my projects but one were gone. I opened `projects.cson` and the projects were there. I pressed `cmd+s` and got the following error: 
```
Failed to load projects.cson
Maximum call stack size exceeded.
```

I am using templates in my projects. Below is my `projects.cson` file.
```json
"proj-template":
  group: "Shore"
merchantsearchwidget:
  title: "Merchant Search Widget"
  template: "proj-template"
  paths: [
    "/Users/Work/Proj/git/merchant-search-widget"
  ]
"shore-core":
  title: "Core (Web)"
  template: "proj-template"
  paths: [
    "/Users/Work/Proj/git/web"
  ]
merchanttablewidget:
  title: "Merchant Table Widget"
  template: "proj-template"
  paths: [
    "/Users/Work/Proj/git/merchant-table-widget"
  ]
team:
  title: "team"
  template: "proj-template"
  paths: [
    "/Users/Work/Proj/git/team"
  ]
merchantappointmentwidget:
  title: "Merchant Appointment Widget"
  template: "proj-template"
  paths: [
    "/Users/Work/Proj/git/merchant-appointment-widget"
  ]
merchanttableadapters:
  title: "Merchant Table Adapters"
  template: "proj-template"
  paths: [
    "/Users/Work/Proj/git/merchant-table-adapters"
  ]
merchantpaymentswidget:
  title: "Merchant Payments Widget"
  template: "proj-template"
  paths: [
    "/Users/Work/Proj/git/merchant-payments-widget"
  ]
tabscomponent:
  title: "Tabs Component"
  template: "proj-template"
  paths: [
    "/Users/Work/Proj/git/tabs-react-component"
  ]
dry:
  title: "DRY"
  template: "proj-template"
  paths: [
    "/Users/Work/Proj/git/dry"
  ]
merchantbookingwidget:
  title: "Merchant Booking Widget"
  template: "proj-template"
  paths: [
    "/Users/Work/Proj/git/merchant-booking-widget"
  ]
```

**Comment by danielbrodin** [comment]
Have you tried reloading Atom after the update?

**Comment by pehota** [comment]
Yes, I restarted Atom several times.

**Comment by danielbrodin** [comment]
Sorry, just noticed you said you restarted after the first error. Not sure what could cause it. What OS do you have? I know it there have been some error on certain Linux distribution before.

**Comment by pehota** [comment]
I am running latest OS X El Capitan. Is there a place where I can see Atom/packages error logs?

**Comment by tfausak** [comment]
I had the same problem with OS X 10.11.4, Atom 1.6.0, and project-manager 2.8.0. I uninstalled project-manager, restarted Atom, and reinstalled project-manager. That fixed it for me.

**Comment by pehota** [comment]
@tfausak ,
Thanks. Unfortunately your suggestion didn't fix it for me.

**Comment by wesbaker** [comment]
I also tried @tfausak's fix and it didn't fix it for me either. I do seem to be able to save my changes and restart Atom and it works. Doesn't seem ideal though.

**Comment by pehota** [comment]
This means I have to go ahead an re-open/re-save all my projects. :/
It seems that the issue only occurs if I try to edit project.cson manually, e.g. paste a project config from my backup or even just open project.cson and hit save.

**Comment by JustinAiken** [comment]
Seeing this too...

- OS X 10.11.4
- Atom 1.60
- Project Manager 2.8.0

Tried uninstalling the plugin, restarting atom, then reinstalling - still get the stack trace error when I try to save the projects.cson

**Comment by tfausak** [comment]
I should have said that I also deleted `~/.atom/projects.cson` and `~/.atom/.apm/project-manager`. I figured that didn't have any effect, but maybe it did.

**Comment by danielbrodin** [comment]
I found some old code still hanging around that I have removed that could perhaps screw with this, so please try updating, reload atom och see if it's any better

**Comment by pehota** [comment]
Still having the same issue :(

- Atom 1.6.1
- Project Manager 2.9.0

I updated, restarted Atom and imported my projects. Upon saving I got that dreaded message again.

**Comment by danielbrodin** [comment]
If you open the developer tools (View > Developer > Toggle Developer Tools), do you get any message there that seems like it could have anything todo with Project manager?

**Comment by pehota** [comment]
No. The console is clean.

**Comment by danielbrodin** [comment]
Sorry, but I have still not been able to reproduce the error which makes it hard to fix it. 
- If you empty the `projects.cson` and use `Project Manager: Save Project` for just one project, does it work then?

**Comment by pehota** [comment]
Using `Project Manager: Save Project` works fine until I try to save more than 2 projects.
The third `Project Manager: Save Project` save attempt brings the issue back.
Maybe it will be helpful to mention that I have several projects opened in separate editor windows.

**Comment by danielbrodin** [comment]
Ohhh, I might have just found the problem. A line of code had for some reason moved up a line so it did a save for each saved project. Please update and try again.

**Comment by pehota** [comment]
Still getting the same error when there are multiple editor windows opened.
Interesting thing I've noticed is that the each window gets the error reported as many times as there are windows open - 1. That is if there are three open editor windows and in the third one I hit `Project Manager: Save Project` the error pops up twice in the first window, once in the second one and it doesn't pop up in the third one.

**Comment by danielbrodin** [comment]
Did you reload each window after updating?

**Comment by pehota** [comment]
This is what I did:
 - update Project Manager
 - quit Atom (no windows)
 - open Atom
 - save project using `Project Manager: Save Project`
 - open another window and load another folder
 - save project using `Project Manager: Save Project` (this caused an error in the first window but not in the second one)
 - open a third window and load another folder
 - save project using `Project Manager: Save Project` (this caused another error in the first window, new error in the second window, no error in the third window)

All projects were saved and are showing up in the list but the error is still there.

**Comment by itamargiv** [comment]
Also Having this problem:

* Ubuntu 14.04
* Atom 1.6.1
* Project Manager 2.9.3

**Comment by itamargiv** [comment]
Attaching the console log, just in case you are still not able to reproduce:

https://gist.github.com/itamargiv/de4a568250439d9a88eda872a39e9112

The stack is very long, tl;dr:
```
    at Object.plus.mapObject (/opt/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:17)
    at Object.plus.deepClone (/opt/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
    at /opt/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:132:31
    at Object.plus.mapObject (/opt/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:17)
    at Object.plus.deepClone (/opt/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
    at Object.plus.deepExtend (/opt/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:152:25)
    at Object.plus.deepExtend (/opt/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:149:32)
    at Project.updateProps (/home/itamar/.atom/packages/project-manager/lib/project.js:59:20)
    at /home/itamar/.atom/packages/project-manager/lib/project.js:151:18
```
Seems like a loop is starting here until memory runs out

**Comment by pehota** [comment]
Nice work. How did you get the stack trace? My console is clean

**Comment by itamargiv** [comment]
I just reproduced the steps with the open console. However, quirky enough, now I can't reproduce the issue...
:confused: I didn't restart Atom nor Ununtu ever since yesterday.

**Comment by joneslloyd** [comment]
Same error as @pehota for me too

**Comment by phw** [comment]
Same here. I noticed that it only happens for a few paths. If I clean my projects.cson completely it works at first. But as soon as I add certain project paths I get the error (with the same stack trace @ itamargiv  posted above). I have not yet figured out what it is that makes those paths special :(

**Comment by danielbrodin** [comment]
Ok, please try the latest patch. Should hopefully fix the issue :)

**Comment by joneslloyd** [comment]
It's still erroring for me unfortunately

**Comment by danielbrodin** [comment]
> deleting the line referencing the config file
Which line would this be?

**Comment by phw** [comment]
From what I can tell with the latest version things got worse. When starting project manager still does not load all projects. When editing projects.cson it doesn't throw an error anymore but hangs infinitely instead :(

**Comment by phw** [comment]
Correction: It does not hang infinitely, it just takes longer as before, than fails with this error:

```
Uncaught RangeError: Maximum call stack size exceeded
/usr/share/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:126
```
Obviously a infinite recursion happening. The stack trace is too long to post here, I have pasted it here:

https://gist.github.com/phw/e158fe316855bcac68f86dfd6fbcf671

**Comment by pehota** [comment]
I upgraded PM to the latest version and restarted Atom. Imported my old `project.cson` and Atom hung taking up more than 100% CPU. I killed it and restarted it, and then PM started working fine. I will post more updates if anything comes up but ... So far, so good.

**Comment by danielbrodin** [comment]
Ok, this time I actually think I have fixed it. An update have been pushed so please let me know if you find any problems.

**Comment by pehota** [comment]
Works perfectly for me :+1:
Thanks @danielbrodin :)

**Comment by JustinAiken** [comment]
Seems to have fixed it for me too! :smile:

**Comment by andradei** [comment]
Thank you, great fix.

OSX 10.11.4
Atom 1.6.2
apm 1.6.0

This issue should be closed.

**Comment by danielbrodin** [comment]
Great :) Thanks all for helping me track down the issue :)
