### ISSUE TITLE
Open Project from Shell?

### ISSUE THREAD

**Issue by ursbraem** [danielbrodin/atom-project-manager#211]
I wan't able to find out on https://discuss.atom.io/t/open-file-project-from-terminal-command-line/1305/19 if it's possible to open atom-project-manager projects (NOT open windows, NOT files) from the shell. Is it, is it not?

Thanks for an answer to this slightly lazy question

**Comment by danielbrodin** [comment]
#130 - Something might have changed since I last tested it though
