### ISSUE TITLE
List Projects showing project multiple times (when it has multiple paths)

### ISSUE THREAD

**Issue by andradei** [danielbrodin/atom-project-manager#215]
The following hypothetical project:

```
myproject:
  title: "My Project"
  paths: [
    "path/to/project/1"
    "path/to/project/2"
    "path/to/project/3"
    "path/to/project/4"
  ]
```

Causes the <kbd>Ctrl</kbd> <kbd>Cmd</kbd> <kbd>P</kbd> (Project Manager: List Projects) command to list _My Project_ 4 times, one per path entered. If the project had 10 paths, it would be listed 10 times.

OSX 10.11.4
Atom 1.6.2
apm 1.6.0
project-manage: 2.9.7

**Comment by danielbrodin** [comment]
Version of the package? Can't seem to reproduce the issue

**Comment by andradei** [comment]
I updated my first comment to include the package version. It is a little odd. I wonder if other packages are responsible for the odd behavior.

I even reinstalled the package to make sure it wasn't a weird fluke.

**Comment by danielbrodin** [comment]
Have you restarted Atom after the last updates?

**Comment by andradei** [comment]
Yes, multiple times.

**Comment by andradei** [comment]
I made some more tests, and the issue only appears when Atom is started from the CLI with one of the paths included in the project:

`atom .` if in the directory of, say, path/to/project/1

or

`atom path/to/project/1` or any of the paths contained in the project.
