### ISSUE TITLE
Correct paths in Windows

### ISSUE THREAD

**Issue by r3nya** [danielbrodin/atom-project-manager#217]
Hi mate!

Unfortunately I need to use windows. :disappointed_relieved: 

I wrote `projects.cson`:
```
common:
    title: 'Common'
    paths: [
        'D:\Projects\common'
    ]

aa:
    title: 'aa'
    paths: [
        'D:\Projects\aa'
    ]
```

And I got `path is not available` message. What did I do wrong?

Btw, 
* Atom 1.6.1
* Project-manager 2.9.7

PS: Thanks a lot for your job!

**Comment by jackplug** [comment]
Looking at my projects.cson file, the paths need to use two backslashes (eg. ``D:\\Projects\\common``)

**Comment by r3nya** [comment]
Hi @jackplug!

It works for me. Thanks a lot! 👍

**Comment by jackplug** [comment]
:+1:
