### ISSUE TITLE
Can't edit project name nor create a new project based on current one

### ISSUE THREAD

**Issue by brunolemos** [danielbrodin/atom-project-manager#218]
**Can't edit project folder name:**
1. Open a project
2. Click Save Project
3. Give a different project name

Expected: The current project is renamed.
Result: Nothing happens.

**Can't create a new project based on current one:**
1. Open a project
2. Add a new project folder
3. Click Save Project
4. Give a different project name

Expected: The current project keeps unmodified. A new project is created. Change to new project.
Result: The current project is updated with the new folder. No new project is created.

**Comment by danielbrodin** [comment]
This should be allowed. What is it that happens?

**Comment by brunolemos** [comment]
@danielbrodin sorry my title / description was completely wrong. Updated it with steps to reproduce.

**Comment by danielbrodin** [comment]
Ok, now I understand :)
1. There is currently no interface to edit a project. I have been wanting to add it, but there haven't been any time.
2. The root path is unique, so only one project can have a certain path as it's root path. It can be added as a secondary path to several projects though.

So to edit the title you currently have to use `Project Manager: Edit Projects` and do it there.

**Comment by billyfan** [comment]
is it possible to make the root path not unique?

I currently have a lot of projects in somewhere like apps/projects, and I have my framework in somewhere like apps/framework, when working on a project, i need access to both the project folder and the framework folder, and sometimes, even the project_v1 and project_v2 if I was doing upgrading work.

So I have to set my atom project root folder to apps/, and in this case, I just can't have multiple atom projects that share the same root folder but opens different files in tabs...

Thanks a lot.
