### ISSUE TITLE
project.cson not working?

### ISSUE THREAD

**Issue by DerNivel** [danielbrodin/atom-project-manager#222]
I now trying for about an hour to get a local settings file working. I just added the `lineHeight` as a test, but nothing changes. I don't know what I'm doing wrong.

```cson
projectmanager:
  title: 'Newww'
  settings:
    '*':
      editor:
        lineHeight: 5
```

**Comment by danielbrodin** [comment]
Is the project added to the the `projects.cson` file?
Have you reloaded atom?

**Comment by DerNivel** [comment]
This is my `projects.cson` file:
```cson
newww:
  title: "Newww"
  paths: [
    "C:\\Users\\Levin\\Documents\\Projekte\\SOME_SECRET_PATH\\Newww\\client"
  ]
```

**Comment by danielbrodin** [comment]
Ahh, sorry, just noticed what is wrong. Local settings skips the first key, so it should be:
```
settings:
    '*':
      editor:
        lineHeight: 5
```

**Comment by DerNivel** [comment]
Now it's working. Thanks!
