### ISSUE TITLE
Suggestion - Default encoding pr. project

### ISSUE THREAD

**Issue by esbenboye** [danielbrodin/atom-project-manager#223]
I work on a lot of different projects and some of them are encoded in ISO-8859-1 and some in UTF-8.
My Atom is set to use UTF-8 as default encoding which is fine when working in UTF-8, but when working on a project in ISO-8859-1, Atom still thinks it is in UTF-8. 

Would it be possible to add a feature, where you could specify a default encoding pr. project and then set that given encoding as default, when opening a project?

I've tried to use a auto detect encoding plugin, but with all kinds of crazy results :)

**Comment by neu-rah** [comment]
this would be nice, i have a module to do that at file level, but I would really prefer a project level setting.
My module (https://atom.io/packages/recall-file-encoding) is relatively new but it seems to work well, and i would not mind to implement this on project manager, with minor guiding about project settings that i've not even investigated yet.
That would be nice if atom provided an encoding drop-list when opening files or folders, but its another discussion of course.
