### ISSUE TITLE
Open Empty Editor on Start

### ISSUE THREAD

**Issue by dannielhugo** [danielbrodin/atom-project-manager#226]
Well, it would be very nice if this package could check for **"Open Empty Editor on Start"** config in atom default settings before opening a new window.

I'm having trouble with this because my files are located in another server and I have to mount it. 

When this server is not available, atom does not open.

**Comment by danielbrodin** [comment]
When would it check for that setting? The package does not open a project automatically on start, only when you do it yourself from the list view.

**Comment by dannielhugo** [comment]
Here it is opening the last project I was using, and when it does, atom get frozen and I can't open it.
Couldn't it be checked at this moment? When does it try to open the "last opened project"?

I'm trying to guess here, as I do not know much about atom and atom-project-manager code.

If there isn't a way to do that, please disregard this issue and feel free to close it.

**Comment by danielbrodin** [comment]
It is atom that is handling that, so should make an issue in the https://github.com/atom/atom repository
