### ISSUE TITLE
Open projects quickly with Atom

### ISSUE THREAD

**Issue by wottpal** [danielbrodin/atom-project-manager#227]
Hey,
_first: Thanks! I really appreciate the work done one the project-manager package. This really eases my daily workflow!_

I'm switching between projects pretty often so if I open Atom it's quite often not the case I want to have the last project I was working on reopened (but I like that behavior nonetheless). So I was thinking about ways to **jump right into a project**, even bevor I've opened Atom:
1. **Right-Click on the dock-item**
   Could it be possible to just add a little separator to the right-click menu and display let's say the most recent 5 projects or so. And if you click on one of them Atom boots up and only opens this project.
   <img width="308" alt="bildschirmfoto 2016-05-27 um 20 37 23" src="https://cloud.githubusercontent.com/assets/3930150/15617822/d80aa846-244a-11e6-90a3-4083145e3edd.png">
2. **Alfred**
   I use Alfred a lot, so I was wondering if there is any kind of API or so that I (or somebody else, who maybe has some alfred-experience) could build a workflow or extend the opening process in some other way.
   <img width="709" alt="bildschirmfoto 2016-05-27 um 20 39 36" src="https://cloud.githubusercontent.com/assets/3930150/15617882/27bd4286-244b-11e6-8b21-93b4327c57d4.png">

What do you guys think?

Regards from Germany,
Dennis

**Comment by ashton** [comment]
I'm a great fan of Alfred too, and I was looking exactly for this right now.

I think we can do this just by creating an alfred workflow to read projects.cson file in ~/.atom directory, that way we can list all registered projects.

To open a project we just run atom [directory path], path which we get from projects.cson file.

I don't have much experience creating alfred workflows, but I'll try to do it, and if it works, I'll post it here.

Any suggestion or comment would be great.

Regards from Brazil :P    o/

**Comment by JustinAiken** [comment]
I like this idea, so I gave it a shot: https://github.com/JustinAiken/alfred-atom-projects
