### ISSUE TITLE
Edit projects in json

### ISSUE THREAD

**Issue by unluisco** [danielbrodin/atom-project-manager#228]
Can I edit the projects with a json file?

**Comment by Sertion** [comment]
Can read about it [here](https://github.com/danielbrodin/atom-project-manager#edit-projects).

**Comment by unluisco** [comment]
there says that projects using a .cson file, but I want to know if can I use a .json file

**Comment by danielbrodin** [comment]
No, `.json` files are not supported. I wont implement it myself, but if you really want it I would accept a PR for it.
