### ISSUE TITLE
Randomly my Project Files dissapear

### ISSUE THREAD

**Issue by showcasefloyd** [danielbrodin/atom-project-manager#229]
I'm on a Mac (OS X 10.11), running Atom 1.7.4 and the latest version of this package 2.9.7. It seems to work perfectly except, that randomly I'll reopen Atom and all my projects are gone. Meaning when I run "List Projects" there are none there any more even though I've saved them with the Save Project command previously.

Any ideas where I can look to try to try and fix this?

**Comment by showcasefloyd** [comment]
Okay, after some digging I found the issue, but I have no idea how to resole it. 

Basically my project.cson file keeps getting renamed to included my computers hostname in it. So instead of just having project.cson it now wants to look for project.hostname.cson. 

This is an issue for me because my hostname on my network is random and changes almost everyday due to some weird setup internally. How can I get Project Manager to just use the default project.cson file and stop looking / messing with anything else?

**Comment by showcasefloyd** [comment]
Okay even after more digging I found I need to disable this feature "environmentSpecificProjects" which as far as I can tell is already turned off, but appears to be doing it anyway.

Thoughts?

    "environmentSpecificProjects": {
      "type": "boolean",
      "default": false
    }

**Comment by danielbrodin** [comment]
That sounds really weird, but I can see no way that environment specific projects would turn on automatically. Have you looked in your `config.cson` to see that the setting isn't there? Or open the Settings view > Packages > Project Manager > Environment Specific Projects and have a look there.

**Comment by showcasefloyd** [comment]
Hey there, I've check in config.cson and have already looked at at the Project Manger ->  Environment Specific Projects  and can confirm that the default is set to false. So why is it not using projects.cson file?

**Comment by danielbrodin** [comment]
It's just the `environment specific projects` setting that checks it. If you open the dev tools `View > Developer > Toggle Developer Tools` and in the console write `atom.config.get('project-manager.environmentSpecificProjects')`, do you get `false` or `true` as the output?

**Comment by showcasefloyd** [comment]
I get "true" But I'm guessing I want false. How do I change this?

**Comment by danielbrodin** [comment]
Have you tried restarting atom? If that doesn't work something weird is going on. You can however change it with `atom.config.set('project-manager.environmentSpecificProjects', false)` from the dev tools

**Comment by aurovrata** [comment]
I am facing the same issue, my project just disappear.  However, in my case the `~/.atom/projects.cson` file just gets overwritten.  This is usually when I save a newly -created project.  I am running Atom on OSx 10.10.5
