### ISSUE TITLE
projects.cson just got wiped

### ISSUE THREAD

**Issue by darylknight** [danielbrodin/atom-project-manager#230]
I just made an edit to one of my projects in `projects.cson`. I saw a red error message about maximum stack size exceeded (Can't remember the exact error) and now my `projects.cson` file is blank, so it looks like I've lost everything.

**Comment by showcasefloyd** [comment]
I think I'm having a similar issue. Every couple of days my entire list of projects just gets deleted. I've started recreating my projects file every few days and still the same issue occurs.

**Comment by darylknight** [comment]
Glad I took a backup; it just happened again upon opening Atom.

![image](https://cloud.githubusercontent.com/assets/1250017/16043864/baa3f490-3239-11e6-82e0-17d063c1d9dd.png)

**Comment by danielbrodin** [comment]
Hmmmm, do you use the template feature?

**Comment by darylknight** [comment]
No - just `title` and `paths`

**Comment by jtinsky** [comment]
I had the same thing happen to me just now.

**Comment by danielbrodin** [comment]
Lets just use one issue #224
