### ISSUE TITLE
Project Titles for Window Name

### ISSUE THREAD

**Issue by jamesstidard** [danielbrodin/atom-project-manager#231]
Hi,

Very much love the project but I work on multiple projects simultaneously so I can get lost with which window is which a lot.

I use OS X and currently it will name the windows with the open file - which isn't really that helpful with projects that share similar structures and naming conventions. Here's a screen shot to show you what I mean from OS X Mission Control:

<img width="540" alt="screen shot 2016-06-22 at 3 58 07 pm" src="https://cloud.githubusercontent.com/assets/1797906/16271684/e2ae3798-3892-11e6-82ef-75b53db55488.png">

It would be nice (if it's possible for your package to modify) have that come up with maybe something like 'Project Name: file_name.js'.

Thanks.

**Comment by DawnPaladin** [comment]
Agreed. I'm on Windows, and seeing the project name in the taskbar would make keeping track of Atom windows much simpler.

**Comment by zpolygon95** [comment]
Check out https://github.com/postcasio/custom-title

**Comment by mirkea** [comment]
+1 for this

How do I make the current project title available for the rest of the app?
Custom title says it supports 'atom global'.

**Comment by davidolrik** [comment]
@mirkea Vote for this pull request: https://github.com/postcasio/custom-title/pull/10
