### ISSUE TITLE
⇧↩︎ could open project with the opposite behavior 

### ISSUE THREAD

**Issue by dkerzig** [danielbrodin/atom-project-manager#232]
Hey guys,
I know in the preferences can be set if a project should replace the current or be opened in a new window but you just don't want the same behavior every time. So i would suggest a shortcut (e.g. ⇧↩︎) for the project-list to open the chosen project with the exact opposite behavior defined in the settings.

Regards from Germany,
Dennis

**Comment by danielbrodin** [comment]
This has been fixed.
