### ISSUE TITLE
Don't always open all recent projects when starting Atom

### ISSUE THREAD

**Issue by dkerzig** [danielbrodin/atom-project-manager#233]
Hey,
maybe it's just me haven't found a way to set this up yet, but I really would like an option that when I start Atom, the project-manager doesn't open up all projects I've opened last time (and all the according opened files). 

In Atom's core settings I've enabled "Open Empty Editor on Start". I suggest project-manager should respect this if it's set. What do you think?
<img width="301" alt="bildschirmfoto 2016-06-28 um 17 03 55" src="https://cloud.githubusercontent.com/assets/3930150/16420645/6b4ff604-3d52-11e6-8e31-f9d12c4585fb.png">

Regards from Germany,
Dennis

**Comment by danielbrodin** [comment]
Project manager shouldn't have anything to do with this. It only tells atom to open a project when you use the projects list view, never on start.

**Comment by dkerzig** [comment]
So is this a bug in Atom or do I completely miss something?

**Comment by danielbrodin** [comment]
@dkerzig That or another package. Have you tried safe mode to see what happens?
Atom provides project manager with the loaded project, so it doesn't automatically load one.

**Comment by dkerzig** [comment]
Unfortunately the behavior the same in safe-mode :( I've filed a bug https://github.com/atom/atom/issues/12075 maybe these guys can help.

Thanks!!
