### ISSUE TITLE
comments deleted in projects.cson

### ISSUE THREAD

**Issue by flurinduerst** [danielbrodin/atom-project-manager#240]
I've got quite a few projects in my `projects.cson` and I need a way to organize/structure them inside the file to not loose the overview. Sadly, if I add comments to `project.cson` they get deleted after restarts. How do you keep the file organized? Could it be possible to allow comments somehow?

**Comment by danielbrodin** [comment]
This would be nice, but https://github.com/atom/season does not support this as it is.
