### ISSUE TITLE
Add option to not disable project paths that do not exist.

### ISSUE THREAD

**Issue by albireox** [danielbrodin/atom-project-manager#242]
project-manager seems to check on start whether a project path exists and, if it does not, it disables the project. This is inconvenient for sshfs mounted projects, as one needs to restart Atom after mounting the ssh disk to be able to use that project. The initial check should be an option in the configuration.

**Comment by draeath** [comment]
+1 here. Ideally there would be a way to have this silently ignored.

**Comment by jolsen71** [comment]
I'd like to extend this request to ask that when if a project is still disabled, that the paths would still be displayed like they are for enabled projects. Right now I have to go to "edit projects" to view the CSON to see the paths if I can't remember where a project lives off the top of my head in order for me to re-connect those mounts
