### ISSUE TITLE
Cannot use customFileTypes?

### ISSUE THREAD

**Issue by davidchall** [danielbrodin/atom-project-manager#243]
I'm trying to configure my project so that it assigns a specific syntax highlighting to files with a `.txt` extension. I want to do this per-project, since `.txt` is fairly ubiquitous.

This is what I have in my `projects.cson` file:
```cson
topas:
  title: "TOPAS"
  paths: [
    "/Users/david/code/topas/src"
  ]
  settings:
    '*':
      core:
        customFileTypes:
          "text.topas": [
            "txt"
          ]
```

But it isn't working. Has anyone done this before? Thanks.

**Comment by danielbrodin** [comment]
It doesn't simply work like that. You would need a topas language package that assigns your files to be of the topas type, whatever that is, haven't heard of it :) I guess you could have a look at [lanaguage-topas](https://atom.io/packages/language-topas)
