### ISSUE TITLE
Request: Could you please add support for menu bar?

### ISSUE THREAD

**Issue by Kaijun** [danielbrodin/atom-project-manager#246]
like [atom-open-recent](https://github.com/Zren/atom-open-recent) does, it added an item in `File` section in menu bar, which is really convenient.

![screen shot 2016-08-17 at 16 22 44](https://cloud.githubusercontent.com/assets/1693027/17739896/f29daa46-6496-11e6-8b12-f92fd8f09d32.png)

So i'm considering if you can also add such support so that we can save/list/open projects from the menu bar?

**Comment by danielbrodin** [comment]
There is a menu item under Packages > Project Manager

**Comment by petersmithca** [comment]
I think they mean, as I would prefer, an option to move to main menu bar, or a way to customize menus.  Digging down through several levels for something I use regularly is not optimal.
