### ISSUE TITLE
Allow individual project files

### ISSUE THREAD

**Issue by FunkMonkey** [danielbrodin/atom-project-manager#25]
It would be nice, if individual projects could be saved in their own files (similar to Sublime).
Could be a setting though, as not everyone might need this.

Thanks!

**Comment by spacedawwwg** [comment]
I like the idea of just having a *project.cson*, which if exists, takes priority over any settings in the global *projects.cson*

as mentioned in this comment https://github.com/danielbrodin/atom-project-manager/issues/25#issuecomment-54783153

**Comment by SusanthCom** [comment]
+1 @FunkMonkey *It would be nice, if individual projects could be saved in their own files (similar to Sublime).*

**Comment by JohannesHoppe** [comment]
I'm used to Visual Studio which uses project files (.csproj) and even solution files to combine projects (.sln). I was really surprised to see that weird global `projects.cson`.

How I’m supposed to share project-related settings across the team? A `project.cson` looks like the best solution.

**Comment by SusanthCom** [comment]
@JohannesHoppe  :+1:

**Comment by danielbrodin** [comment]
I have been wanting to get started on adding support for a `project.cson` that could be stored in the project root, but I haven't had time. Have a lot of other things happening now.

I still think I only want settings in that file though and keep the project with it's location in the `projects.cson` file still. So it can function just like it does for those that want to keep it simple, and if you want to store the settings, and maybe something else that will be supported with the project, you will save the project in the `projects.cson` like it is now, but also create a `project.cson` in your projects root which will store settings etc...

Does that sound good or are there any other ideas?

Just so you know, I really dislike the way sublime has it where the projects list pretty much is a cached list of projects that have been opened and it forces me to save it somewhere, and as soon as I move or delete a projects file it's not up to date anymore. So thats the big reason I made the package as simple as it is with all projects being saved in the `projects.cson` file. I do however agree that storing settings of all sorts together with the project is a good idea.

**Comment by schmurfy** [comment]
I think that's a good compromise :)
I also don't like all sublime is doing, this pile of garbage stored in the workspace file is really ugly.

**Comment by SusanthCom** [comment]
@danielbrodin  Thats a good move ! :heart: 
Please move ahead :+1:

**Comment by danielbrodin** [comment]
Just an update to this. I have found some time here and there to start implementing this. I have done (not released yet) an implementation for testing it that looks for a local `project.cson` file and merges those settings with what is in the `projects.cson` file, so all you would need to save in `projects.cson` would be the path pretty much.
```
myproject:
  paths: ['project/path']
```

Currently the implementation doesn't automatically update the project when updating the local settings though, only the settings in `projects.cson`. Haven't decided how to do that yet, but this is the status of it at least :)

**Comment by danielbrodin** [comment]
Just wanted to let you know that keeping a `project.cson` file in the root directory is now supported :) The project must still currently be saved and kept in the `projects.cson`, but an initial save with title and paths is enough, rest of the settings can be in the `project.cson`.

**Comment by schmurfy** [comment]
nice ! thanks :)

**Comment by lzkelley** [comment]
@danielbrodin does this address the issue over in https://github.com/atom/atom/issues/5168?
