### ISSUE TITLE
[3.0] Settings don't seem to work anymore

### ISSUE THREAD

**Issue by JustinAiken** [danielbrodin/atom-project-manager#251]
I have a project with these settings:

```cson
    name: "my_proj"
    settings:
      core:
        ignoredNames: [
          "_build"
          "tmp"
          ".git"
          "deps"
          ".tags"
          ".tags1"
          "node_modules"
        ]
```

..but upon updating to 3.0, all these ignored folders are popping up.  

- This is true if the settings are directly in the project, or if they're in a referenced template.
- This seems to be affecting all of my projects, not just an isolated case..
- If I do `atom.config.settings.core.ignoredNames` in the atom console, the list returned is my defaults, not the project ones.
- This is the case whether I explicitly load the project through the command palate, or if I quit/restart Atom and it remembers the window

**Comment by JustinAiken** [comment]
..also is the case if I try it with this syntax:

```cson
    settings:
      'core.ignoredNames': [
        "_build"
        "tmp"
        ".git"
        "deps"
        ".tags"
        ".tags1"
        "node_modules"
      ]
```

**Comment by danielbrodin** [comment]
I know what the issue is and have fixed it, not on my usual computer though so having some issue publishing the fix. Will come tomorrow though

**Comment by JustinAiken** [comment]
Hmm, updated to 3.10, restarted Atom, afraid I'm still seeing the behavior
