### ISSUE TITLE
Problems and questions regarding the exposed service

### ISSUE THREAD

**Issue by Gert-dev** [danielbrodin/atom-project-manager#252]
Hello

Since about a month ago, I started depending on this package for PHP project management in php-integrator, a choice which I have not regretted so far. I see you've released version 3.0 today, and it's great to see that this package, which provides such an important piece of missing functionality in base atom, is still being actively developed.

I've just updated to 3.0 and am experiencing a couple of issues, some of which are more questions than actual problems.

The service exposed by this package has changed and broken compatibility (which is fine, it is a major release, after all), but it seems you've forgot to bump the service version in `package.json`. It is currently still at `2.3.0`, causing my package, which depends on it, to try to use it as if it was still the old one. Should this perhaps be updated to `3.0.0`?

I see the exposed `projects.getCurrent()` has been replaced with just `getProject()`. However, they seem to behave slightly differently as, where previously I could call this immediately after the service was injected, it now returns `undefined`. I noticed that this is probably because project manager is not done loading the project yet, as when I call it after a timeout, it does return the project. This puts me a difficult position, however: I can't load the active project as soon as the service is injected and loading after a timeout is not really great practice. Is there any way I can register a callback with this package that will notify me if the active project changes? I also won't be able to support project switching inside the same window (which previously wasn't necessary as it wasn't supported) if I don't know when the active project changes.

Finally, how do I update the properties of a project? Previously I could use `project.set()`, but that seems to have disappeared. `project.updateProps` seems to have no effect on persisting the settings either.

Also, a little bit off-topic: have you thought of trying to get this package to be bundled with Atom itself? There are a couple of project management packages, but this is by far the most popular and is one of the few that supports project-specific settings, which opens up possibilities for other packages to store project-specific settings for indexing and such.

Thanks in advance

**Comment by danielbrodin** [comment]
Hi, I'm so sorry. Completely forgot to up the version and make sure the old service api worked.

`getProject()` should run your callback each time a project is triggered. The first time that could be null, but when it's loaded it should run again with the project, and after a project change it should run once again.

If you do a check to see if there is a project that should be enough for you I hope? Or do you have any special needs?

There have been a lot of structure changes so simply adding the changes to the project (`project.updateProps()` wont work. It was a nice idea I had, but it had some issues, but I could provide something like a `updateProject(project, props)` or perhaps just `saveProject(project)`


About getting merged into the Atom core, no, I haven't really given it much thought, but if they would be interested in it why not :) 

Btw, what is the package you have done?

**Comment by Gert-dev** [comment]
Thanks for your reply and for clearing up the behavior of the `getProject()` call, I expected it to be a fire-once type of method like before, but see now that it indeed acts as a register-an-event-handler type of method. That already fixes one of my workarounds.

What I'm currently still missing is a way to somehow persist project settings after applying changes to the getProps() object. I previously used the `project.set()` method for this, which automatically seemed to persist as well. I think your suggested `updateProject` or `saveProject` method more than suffices for my use case here :+1: .

Finally, the package I'm writing is [php-integrator](https://github.com/Gert-dev/php-integrator-base), which provides indexing and analysis for PHP projects for things such as autocompletion, code navigation and tooltips. I had been delaying introducing project support for quite some time in the hope that an official package would arise, but there are several issues that are very hard to solve without some notion of project settings, such as configuring excluded folders and the PHP version of the project. Since your package provides a service to read and persist new settings to a project, it was an ideal way for me to implement those features. For example, the refactoring package can check the PHP version configured in the project settings to decide whether or not it can generate code with PHP 7 support automatically.

**Comment by danielbrodin** [comment]
Hey, I have done a new release now where there is a `saveProject(project)` method. It can either take a project recieved from `getProject()` or `getProjects()`, or an object containing the properties for a new project. Please let me know how it works out.

I have also updated the provider version to 3.1.0, so you will probably have to do that as well.

Your package sounds interesting. I'm doing a lot of php development at work, so will have a look at it next week :)

**Comment by Gert-dev** [comment]
Great to hear! Thanks to your quick response and update, I've just published a new patch release of my package that has all its previous functionality restored.
