### ISSUE TITLE
projects.cson: what’s with the brackets?

### ISSUE THREAD

**Issue by danielbayley** [danielbrodin/atom-project-manager#253]
Eww… I just saved a project and now my relatively tidy `projects.cson` is full of noise.

If this is how it has to be now, you might as well use JSON?

**Comment by danielbrodin** [comment]
Having an unnecessary key isn't that much nicer imo, and it could have been json perhaps, but a bit late to change to that, and cson is still a bit cleaner.

One of the current goals is to make an interface so you wont even have to look directly at the `projects.cson` file, so then you wont have to have the "eww" feeling anymore ;)

**Comment by danielbayley** [comment]
Actually I think ultimately there shouldn’t _be_ a global `projects.cson` at all, given that Atom is already keeping track (see _project-plus_), and instead everything is read from a local `project.cson` file…
