### ISSUE TITLE
Per-project Setting does not work since v3.0.0

### ISSUE THREAD

**Issue by dwoutsourcing** [danielbrodin/atom-project-manager#256]
Before 3.0. upgrade I was able to define a list of disabled packages in a per-project basis. Since v3.0.0 it stop working. projects.cson is 

`[
  {
    title: "Test project"
    group: "jmail"
    paths: [
      "C:\\xampp\\htdocs\\test_project"
    ]
    icon: "icon-chevron-right"
    settings:
      "*":
        core:
          disabledPackages: [
            "atom-bootstrap3"
            "atom-bootstrap4"
            "language-smarty"
            "rest-client"
            "Remote-FTP"
          ]
    devMode: false
    template: null
  }
]`

**Comment by danielbrodin** [comment]
Updating the package should fix this :)

**Comment by dwoutsourcing** [comment]
Thanks for your answer. 
I've updated the package to v3.0.1 and after that to v3.1.0 and per-project settings still do not work.
