### ISSUE TITLE
close current settings no longer works

### ISSUE THREAD

**Issue by sagiegurari** [danielbrodin/atom-project-manager#257]
With latest update (3.1.0) the 'Close Current' setting set to checked in the UI, no longer works.

**Comment by danielbrodin** [comment]
It has been replaced with shift+enter from the list view.

**Comment by sagiegurari** [comment]
1. I don't use keyboard. Got a toolbar.
2. you have a checkbox in the settings that does nothing?
3. why remove it?

**Comment by danielbrodin** [comment]
1. How does the toolbar implement project manager?
2. The setting is gone, no idea why Atom have kept it for you
3. The new implementation is a lot better

**Comment by sagiegurari** [comment]
so I have a key in the toolbar that opens the project select dialog and than I just press with the mouse on the project I want to open (and close current project).
Since I'm already pressing with the mouse on the toolbar to open the project select dialog it makes not sense to start working with keyboard in the middle of this flow.

Better is really kind of a perspective thing. UX is tricky subject.

**Comment by danielbrodin** [comment]
Oh, I wasn't talking about UX, the coding implementation is better in that it doesn't open in a new window and then closes the old one, it opens in the same window, so the name of the option is all wrong now.

Anyway, update the package and you will find an option to always open in the same window as the default :)

**Comment by sagiegurari** [comment]
thanks :+1:
