### ISSUE TITLE
Multiple folders per project

### ISSUE THREAD

**Issue by johngeorgewright** [danielbrodin/atom-project-manager#259]
Since an update today, all my projects that had multiple folders have been reduced to 1, and after adding them they don't get saved automatically; I need to add them manually in the CSON file.

**Comment by mariusvw** [comment]
Having the same issue, I noticed that the CSON file was also having all default keys which I skipped in my own file.
Re-adding the paths made no change, when opening up the project it gets reverted back to the first path in the list.
Atom: 1.10.2
Package: 3.2.0

**Comment by danielbrodin** [comment]
Please update and try again. Should be fixed now.

**Comment by mariusvw** [comment]
Seems to work fine again, thank you very much for the quick fixing 👍

**Comment by johngeorgewright** [comment]
Ta.
