### ISSUE TITLE
Per-project Setting does not work since v3.0.0

### ISSUE THREAD

**Issue by dwoutsourcing** [danielbrodin/atom-project-manager#260]
Before 3.0. upgrade I was able to define a list of disabled packages in a per-project basis. Since v3.0.0 it stop working. projects.cson is

[ { title: "Test project" group: "jmail" paths: [ "C:\\xampp\\htdocs\\test_project" ] icon: "icon-chevron-right" settings: "*": core: disabledPackages: [ "atom-bootstrap3" "atom-bootstrap4" "language-smarty" "rest-client" "Remote-FTP" ] devMode: false template: null } ]

**Comment by JustinAiken** [comment]
Me too - is still broken in 3.20

**Comment by jnettik** [comment]
I'm new to using Atom, but I believe my issue is similar. I want to configure the path settings for php-debug per site. The config.cson settings looks like:

```
  "php-debug":
    PathMaps: [
      "/var/www/site;/Users/jnettik/Sites/site"
    ]
```

I would assume the projects.cson setting would be:

```
    settings:
      "php-debug.PathMaps": [
        "/var/www/path;/Users/jnettik/Sites/path"
      ]
```

It would be handy to be able to tie the debugger pathing to it's project settings, and not have to define them globally. Thank you for any help you can give!

**Comment by danielbrodin** [comment]
Hmm, the tests I did got it working, but it's not working for me either now. Will have a look at it

**Comment by danielbrodin** [comment]
So, please update and try again :)

**Comment by jnettik** [comment]
I'm still having issues with the php-debug plugin on this. I add my path maps as a project setting and nothing happens. Move the same setting over into my config.cson and it works fine. Am I doing something wrong when moving the path maps into projects.cson?

**Comment by JustinAiken** [comment]
It works now!! 😂 

Thank you :)

**Comment by danielbrodin** [comment]
@jnettik It could be that the php-debug package only looks at that `config.cson` and not at the settings from atom.

**Comment by jnettik** [comment]
Good to know. I will reach out on that project. Thank you for your quick replies and work on this.

**Comment by danielbrodin** [comment]
@jnettik I looked at the package page and it should read from it, but could be that it doesn't listen for changes and the settings from your project is added after it has read it's setting.
