### ISSUE TITLE
Bug: "Close Current" doesn't work

### ISSUE THREAD

**Issue by darylknight** [danielbrodin/atom-project-manager#262]
When I switch between projects with `ctrl + cmd + P`, the current project stays open and it opens a new project in a new window. I've got the "Close Current" setting ticked, so it's not working.

EDIT: I've now ticked "Always open in the same window" which seems to do what "Close current" used to do. So what is Close Current used for now?

**Comment by danielbrodin** [comment]
Close current is removed. You only have it because you had it ticked before, or maybe atom cached it somehow.

**Comment by rzelnik** [comment]
I also can confirm that I still have the "Close Current" option. I tried to uncheck this option, uninstall, restart Atom, install again. It's still there.

**Comment by gavinr** [comment]
@danielbrodin thanks for the great Atom package! I use daily and really like it.

I still have "Close Current" too (`v3.3.3`) - if this is not supported anymore, how do I remove it?

**Comment by danielbrodin** [comment]
@gavinr It is not supported, and not even in the code anymore so probably just something cached. If you edit the config file directly and remove it from there I'm pretty sure it will disappear.
