### ISSUE TITLE
Can't save new project

### ISSUE THREAD

**Issue by TitanNano** [danielbrodin/atom-project-manager#263]
I'm unable to save a new project anymore.

I get this nice UI but nothing happens when I click the save button.
![screen shot 2016-09-14 at 11 12 43](https://cloud.githubusercontent.com/assets/4500858/18506388/2e950996-7a6c-11e6-87d5-f58463ac4b7e.png)

**Comment by TitanNano** [comment]
apparently it seems that the project has been saved, but the UI just doesn't respond.

**Comment by summit-web** [comment]
It might be linked to this issue:
https://github.com/danielbrodin/atom-project-manager/issues/254

(restarting Atom after closing it completely may fix your issue too)

**Comment by danielbrodin** [comment]
Ahh, yeah, the UI just doesn't respond atm. Bad UX, I know, but it's still work in progress and I haven't decided how it should work yet.

**Comment by BenoitAverty** [comment]
My two cents : This should work as before. Not necessarily remove the new options (I guess they are nice for some), but the previous workflow should still work.

In my case : 
- Ctrl+Shift+P (command palette)
- Type prsa to select "Project manager: Save Project"
- Enter to make the window appear
- Enter again to validate (the suggested title was good for me in most case)
Done !

Now I have to click on the "Name" field, type a name, then click "enter" and close the tab. This shouldn't be mandatory.
