### ISSUE TITLE
"Close Current" option does not work in new version

### ISSUE THREAD

**Issue by modulexcite** [danielbrodin/atom-project-manager#267]
Thank you for the extension.
I upgraded to the new version and "close current" option stopped working. 

**Environment:**
- OS: Windows 7 SP1
- Atom: 1.10.2
- Atom-Project-Manager: 3.2.1

Let me know if you need more info.

**Comment by danielbrodin** [comment]
It has been replace with either using `shift+enter` in the projects list or by setting `Always Open In Same Window` to true.

**Comment by modulexcite** [comment]
I'm not following. I would expect it to close the current instance of atom if I'm not using "shift+enter" and have set the following options 
**Close Current** - Enabled 
**Always open in Same Window** - Disabled
