### ISSUE TITLE
Project list not clear

### ISSUE THREAD

**Issue by izcream** [danielbrodin/atom-project-manager#269]
i remove atom and install again and install project manage package
but my old project list still show in projectmanager>list.
i try to remove projects.cson and reload all projectmanager setting but list still show

how do i fix it?

Thanks 
ps. sorry for my bad english

**Comment by danielbrodin** [comment]
Do you have the Include Git Repositories setting on?

**Comment by izcream** [comment]
i uncheck git repositories but projects list still show

**Comment by izcream** [comment]
updated now i resinstall atom and package projects list is cleared :)
