### ISSUE TITLE
Add a project-specific "session"

### ISSUE THREAD

**Issue by davidkaneda** [danielbrodin/atom-project-manager#27]
One of my favorite features in Sublime Text is the fact that projects have their own session/workspace area which automatically tracks unsaved changes, unsaved files, and open tabs. The benefit is that I can close a window (or switch projects) with unsaved files/changes, without any warnings or confirmations — the changes are simply re-applied when I re-open the project.

Combined with the "Close Current" option (and #18), this makes for a super elegant workflow when switching between projects-

**Comment by nicolasmccurdy** [comment]
:+1:

**Comment by redders6600** [comment]
:+1: 
This is the number one issue stopping me from using atom full time at the moment, I'd love to see this implemented.

**Comment by KangarooCreativeTeam** [comment]
MEH.

I came here looking for a possible bug because I've lost all the tabs of my closed projects. 

If this is how it works - then **EPIC SADNESS**. 

I too ~~used~~ use Sublime Text where the flow is _effortless_.  
Without this functionality; is there any real difference between opening a project vs simply dragging my folder to atom?

I've totally lost my focus, & have to remember what files were last open. 

**EPIC SADNESS INDEED.**

O_O

-- HEAD KANGAROO
KangarooCreativeTeam.com
_(New site up next week!)_

**Comment by KangarooCreativeTeam** [comment]
I've just come across other relevant bugs: 

#37 & #78 for tracking open tabs (reopening tabs on project load):
They point to installing this atom package:  [save-session](https://atom.io/packages/save-session)

[#942](https://github.com/atom/atom/issues/942) is relevant for automagically remembering unsaved changes.  It tooo points to:  [save-session](https://atom.io/packages/save-session) 
(which supports  _unsaved_ (scratchpad) tabs and also unsaved _changes_ of (prior saved) tabs!)

[save-session](https://atom.io/packages/save-session) package's relevant info:

> _"It automatically saves all file's contents in the background so you don't have to worry as much about losing an important file. I liked how Sublime Text does this, so I wanted to recreate it for Atom."_

> _"File info is stored in a folder at \<atom package dir\>/save-session/**\<project path\>**/projects.json by default and gets reloaded at when you reopen the same **project** again."_

(so it supports per-project, and _not_ just globally for all of atom)

> _"Skip Save Prompt - This will disable the save on exit prompt."_

(so you _can_ just exit anytime without getting nagged to save)

> _"Check out this issue ([#942](https://github.com/atom/atom/issues/942)) for the status of this functionality being added to Atom core"_

So; it'll eventually be in atom core (as it really should be). 

#89 is relevant too (concerning re-opening of tabs).  It gives a workaround of loading the project _twice_ (however this does _not_ always work, if the state has already been lost #FML). 

I have made some progress on when the error occurs (to make it somewhat reproducible, so it can be fixed moar quickly).  I will **not** be updating this bug, as it's functionality is mostly available in [save-session](https://atom.io/packages/save-session) (until it arrives in atom core proper).  If you want to follow progress, I suggest #89 & [#942](https://github.com/atom/atom/issues/942)

/END EPIC LONG POST

O_O

-- HEAD KANGAROO
KangarooCreativeTeam.com
(New site up next week!)
