### ISSUE TITLE
"No projects saved yet" errors

### ISSUE THREAD

**Issue by darylknight** [danielbrodin/atom-project-manager#270]
Periodically when I add or update a project, I'm then no longer able to use project manager to switch between projects. After making an update to projects.cson, I then try to switch projects and the switching dialogue just says `"No projects saved yet"` even though the projects.cson file still has all the entries in it. Even when I get rid of the change I made to the projects file, the error still persists and I can't use it anymore.

Yesterday I rebuilt the whole file from scratch and it was fine. Today I try to switch projects and I'm getting the same error again.

**Comment by danielbrodin** [comment]
If you run `Window: Toggle Dev Tools` from the command palette and pick `Console`, do you see any errors that has to do with the project manager?

**Comment by pistou** [comment]
I have the same issue.
*Fun* fact, I now have a `projects.desktop-7ffitun.cson` file while I only had `projects.cson`.
Both structures seems quite differents though:

**projects.cson**:
```
project1:
  title: "TITLE 1"
  group: "GROUP",
  paths: [
    "C:\\Users\\Pierre...."
  ]
  settings:
    "*":
      "core.fileEncoding": "iso885915"
project2:
  title: "TITLE 2"
  group: "GROUP",
  paths: [
    "C:\\Users\\Pierre...."
  ]
  settings:
    "*":
      "core.fileEncoding": "utf8"
```


**projects.desktop-7ffitun.cson**:
```
[
  {
    title: "TITLE 1"
    group: "GROUP",
    paths: [
      "C:\\Users\\Pierre...."
    ]
    settings:
      "*":
        "core.fileEncoding": "iso885915"
  },
  {
    title: "TITLE 2"
    group: "GROUP",
    paths: [
      "C:\\Users\\Pierre...."
    ]
    settings:
      "*":
        "core.fileEncoding": "utf8"
  }
]
```

**Comment by darylknight** [comment]
I think I've traced this to whitespace. When I get the error, if I then edit the projects.cson file, select the whole lot and press my "auto indent" key, it fixes the issue.... I think.

**Comment by danielbrodin** [comment]
@darylknight yeah, both `cson/json` is really sensitive to errors. I should probably notify about errors.

@pistou You have enabled `Environment Specific Settings` which gives you the second file. The structure has also changed between major versions, so the second one is the latest.

You could download a coffeescript linter if you want to see where the error is before I have added a notification.

**Comment by pistou** [comment]
Nice, thanks 👍

**Comment by darylknight** [comment]
Thanks :)
