### ISSUE TITLE
Can't save new project

### ISSUE THREAD

**Issue by smlombardi** [danielbrodin/atom-project-manager#271]
1. Bring up command panel, Project Manager:Save Project
2. New window appears with defaults, but are un-editable.

Atom 1.11.0-beta5, Project Manager 3.2.3, macOS 10.12.

![screen shot 2016-09-26 at 9 25 51 am](https://cloud.githubusercontent.com/assets/835148/18835854/3de22592-83cb-11e6-9ff2-d9e19393ff5a.jpg)

**Comment by danielbrodin** [comment]
Hmm, could it be your theme or another package? Can't think of a reason why they should be disabled.

**Comment by smlombardi** [comment]
I could not see the fields to add my project info into.  My theme (Material Theme) must make them too dark to see.  Suggest you make the fields a light color or put the focus into the title field by default?
