### ISSUE TITLE
Filter project by group

### ISSUE THREAD

**Issue by resilva** [danielbrodin/atom-project-manager#272]
I've searched in issues and options but doesn't found a way to filter from group while openning a project.  The usecase is instead of searching project by name when triggering `alt+shift+p` it could be cool to search by group.

**Comment by danielbrodin** [comment]
It's in the read me, just prefix the search with `group: ` :)

**Comment by resilva** [comment]
My bad reading it too fast, thanks a lot @danielbrodin ;)
