### ISSUE TITLE
Show git status along side Projects List

### ISSUE THREAD

**Issue by BarryThePenguin** [danielbrodin/atom-project-manager#274]
Similar to how the [fuzzy-finder works](http://blog.atom.io/2014/03/13/git-integration.html#git-status-list) it would be great to see the current git status of projects within the Projects List in in the Command Palette.

Atom provides access to [`atom.project.repositoryForDirectory`](https://atom.io/docs/api/v1.10.2/Project#instance-repositoryForDirectory) which returns a [`GitRepository`](https://atom.io/docs/api/v1.10.2/GitRepository). This provides cached git status information.

**Comment by danielbrodin** [comment]
Sorry for the late answer, but yes, this would be a nice feature. I do think however that the `GitRepository` class is made only for the currently loaded project so would possibly need another solution, unless `GitRepository` is using something else that could be used
