### ISSUE TITLE
Can't change customFileTypes setting 

### ISSUE THREAD

**Issue by DBosley** [danielbrodin/atom-project-manager#281]
I'm trying to set up my project to pull in nunjucks templating language highlighting, but I can't get the settings configuration to work properly.

Here is my 'settings' configuration:

```
[
  {
    title: "site"
    paths: [
      "C:\\_DEV\\site"
    ]
    settings:
      "editor.showInvisibles": true
      "core.customFileTypes":
        'text.html.nunjucks': [
          "html"
        ]
  }
]
```

The 'editor.showInvisibles' setting does work, but the 'core.customFileTypes' setting does not.

**Comment by danielbrodin** [comment]
I wasn't aware of the `core.customFileTypes` settings. Is it even available? Anyway, have you tried using the [langague nunjucks](https://atom.io/packages/language-nunjucks) package instead?

**Comment by DBosley** [comment]
It's the top entry on the core config options. 
http://flight-manual.atom.io/using-atom/sections/basic-customization/#configuration-key-reference

I do have the 'language nunjucks' package installed, it's what sets up the 'text.html.nunjucks' scope, but it associates to *.html.nunjucks files and not *.html. The project I'm using requires the nunjucks views to end with .html, so I wanted to set a project-level config to use the 'nunjucks language' with html files. I wanted this to work at the project level because I didn't see any good reason to have all html files set up with nunjucks highlighting for every project I work on. But I can't seem to set 'customFileTypes' as a project level config.

I did set the setting directly in my atom config.cson just to make sure it works the way I expect it to, and my html nunjucks highlighting worked perfectly.

**Comment by danielbrodin** [comment]
Nice, didn't know about it. Not sure why it doesn't work, but I will see if I can find something.

**Comment by juliovedovatto** [comment]
I tried another approach, using file-types plugin (https://atom.io/packages/file-types). But without success

```cson
[
  {
    title: "Project"
    group: "Personal"
    paths: [
      "/Users/juliovedovatto/Sites/Project"
    ]
    settings:
      "file-types":
	      ".html": "source.swig"
  }
]
```

I need .html files on this projects needs to be opened with swig syntax highlighting. Does it make sense? Is that possible with Project Manager?

**Comment by juliovedovatto** [comment]
@DBosley I managed to do this using the ```file-types``` package:

```cson
[...]
settings:
  "*":
    "file-types":
      "html": "source.swig"
```

In my case, I need to open .html files using SWIG syntax highlighting.

I hope this can help you. This issue helped me to find a solution :)

Cheers

**Comment by GizMecano** [comment]
I've tried these two methods in a `project.cson` to test displaying `.txt` files as C++ language, and both don't seem to work.

With the `customFileTypes` method:

```coffee
[
  {
    settings:
      'core.customFileTypes':
        'source.cpp': [
          'txt'
      ]
  }
]
```

With the `file-types` method:

```coffee
[
  {
    settings:
      "*":
        "file-types":
          "txt": "source.cpp"
  }
]
```

In the first case, I wonder if the issue could refer to the (missing) asterisk position (mentioned in [customizing language recognition](http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition)), and in the second, if the use of single or dual quote marks could be in question... 🤔

**Comment by gizmecano** [comment]
To make a little minor update about this issue, I have finally understand that in order to correctly configure this kind of settings, using [`file-types` extension](https://github.com/execjosh/atom-file-types), you may not add a specific `project.cson` in the root of your project, but you must manually change the  main unique `projects.<user>.cson` (note the use of the plural in the file name).

So adding a definition such this works properly:

```cson

[
  {
    title: "project-title"
    paths: [
      "C:\\path\\project"
    ]
    settings:
      "*":
        "file-types":
          txt: "source.cpp"
  }
]

```

Hoping that it can help...
