### ISSUE TITLE
What does Dev mode means? Could you explain?

### ISSUE THREAD

**Issue by jitendravyas** [danielbrodin/atom-project-manager#283]

**Comment by danielbrodin** [comment]
It's an Atom thing

> Development mode loads the Atom source from the locally cloned repository and also loads all the packages in ~/.atom/dev/packages

It's so you can have both the released version and a development version installed at the same time, so you normally use the released version, but while in dev mode the dev version is used instead.

**Comment by vbrozik** [comment]
In such a case I think that the option should be renamed to "Atom development mode" or something similar.
