### ISSUE TITLE
Support for Material Icons

### ISSUE THREAD

**Issue by bennypowers** [danielbrodin/atom-project-manager#287]
Material Design icon fonts don't use classes to refer to individual glyphs, instead drawing the reference from the content of the tag

    <i class="material-icons accessibility"></i> 
    <i class="material-icons">accessibility</i> 

It would be swell if `atom-project-manager` would support a scheme like this.

**Comment by BarryThePenguin** [comment]
Can you provide some more info? It's not clear on what "Material Design icon fonts" are and how they are different from the current icons?

**Comment by bennypowers** [comment]
Sure!
To render an octicon in the browsers, you use this markup: `<div class="icon icon-globe"></div>`. Similarly, to render fontawesome, you use `<i class="fa fa-globe"></i>`. Material icons use a different markup syntax: `<i class="material-icons">language</i>`. 

In the case of material icons, the specific glyph is determined based on the innerHTML of a `.material-icons` elem.

**Comment by BarryThePenguin** [comment]
But what are material icons?

**Comment by bennypowers** [comment]
https://material.io/icons/

**Comment by danielbrodin** [comment]
Some changes would have to be made to implement it, but I'm sure it could be fixed. Not on my priority list, but a PR would be welcome :)
