### ISSUE TITLE
Uncaught Error: The element has already been freed!

### ISSUE THREAD

**Issue by DeanmvSG** [danielbrodin/atom-project-manager#288]
(Going to lazy here) But all of the details are here - https://github.com/atom/atom/issues/13137#issuecomment-258155877

Let me know if you need anything more!

**Comment by danielbrodin** [comment]
I haven't been able to reproduce it so some steps to do that would be helpfull

**Comment by DeanmvSG** [comment]
@danielbrodin I haven't had it in a while to be honest.  It was happening "randomly" before and hasn't since I've done a few beta updates.

I'll mark as closed for now as it doesn't seem to be an issue,  if anyone else that 👍 it has some steps to reproduce then I'll re-open!
