### ISSUE TITLE
project.cson is not working

### ISSUE THREAD

**Issue by guiguan** [danielbrodin/atom-project-manager#290]
The per project settings in project.cson are not loaded

**Comment by danielbrodin** [comment]
Could you show how your `project.cson` file?

**Comment by taschetto** [comment]
I have the same problem. I need differente tab lengths among projects but this doesn't work.

```[
  {
    title: "Project A
    group: "Projects"
    paths: [
      "C:\\projects\\A"
    ]
    settings:
      'editor.tabLength': 2
  },
  {
    title: "Project B"
    group: "Projects"
    devMode: true
    paths: [
      "C:\\projects\\B"
    ]
    settings:
      'editor.tabLength': 4
  }
]```

**Comment by NickWhiu** [comment]
I am wondering if Project Manager is not notified when atom is opened and the last project folder is automatically opened (as if atom opened the folder instead of user goes to Project Manager projects list and manually opened a project)

**Comment by danielbrodin** [comment]
Hmmm, I gues there could be something overriding the settings. Are you using the editorconfig package or something similar?

The settings feature is a but bugged because of pretty crappy support for doing what it does, so it would probably need some more love and investigating what is possible.

**Comment by ryanjbonnell** [comment]
Yes, I'm using the popular [EditorConfig package](https://atom.io/packages/editorconfig) among others.

I'll try to do some testing of whether disabling EditorConfig improves or fixes the `project.cson` behavior in Project Manager.

I wonder if others are having the same incompatibility?

**Comment by ashl1** [comment]
Not worked for me too. I don't use EditorConfig but core per-language settings:
```
[
  {
    title: "Redux Actors"
    paths: [
      "/home/user/projectA"
    ]
    settings:
      'editor.tabLength': 4
      '.js.regexp.replacement.source.editor.tabLength': 4
      '.js.regexp.source.editor.tabLength': 4
      '.js.source.editor.tabLength': 4
  }
]
```
