### ISSUE TITLE
Question: exclude sub folders from project?

### ISSUE THREAD

**Issue by simahawk** [danielbrodin/atom-project-manager#292]
I wonder if i possible to exclude some folder from a project.

Consider the following structure:

- proj root
    - a
    - b
    - c

whereas proj root is the main folder and contains also folders and files that I want to edit. `b` is a sub folder that I want to ignore (but it's name/path could change from project to project).

ATM I do `atom path/to/root` but this loads all items in the root and sub folders and looks like there's no way to exclude `b` or any other item on demand. In tree view I find "add folder to project" or "remove folder from project" but it works only at root level.

**Comment by JustinAiken** [comment]
```cson
    settings:
      core:
        ignoredNames: [
          "some_folder"
          ....
        ]
```

**Comment by simahawk** [comment]
@JustinAiken works! thanks :smile:
