### ISSUE TITLE
Not compatible with sync-settings

### ISSUE THREAD

**Issue by MaximilianR** [danielbrodin/atom-project-manager#295]
Currently it doesn't look as though [sync-settings](https://github.com/atom-community/sync-settings) is backing up `projects.cson`. 

Is it feasible to put the settings in a file that sync-settings would back up? Or should sync-settings be backing up a wider range of files?

Thanks for the package!

**Comment by danielbrodin** [comment]
I haven't used the package myself, but it seems to have a `extraFiles` setting where I guess you could add the `projects.cson` file. Doesn't seem to be a way for me to register the `projects.cson` file as something that could be synced, so for an option it would have to be added directly to the package.

I hope that helped you :)

**Comment by MaximilianR** [comment]
That worked! 

It was all on the other package. 

Thanks for responding so promptly, and again for project-manager!
