### ISSUE TITLE
"No symbols found" in file view when open project with Project Manager

### ISSUE THREAD

**Issue by judewang** [danielbrodin/atom-project-manager#296]
Recently, I found sometimes there are no symbols found when I press cmd + r. After searching and trying to fix the problem, I found a possibly [answer](https://github.com/atom/symbols-view/issues/177). Opening a project from command line is the only workaround I could find so far.

**Comment by danielbrodin** [comment]
Do you get the same result opening a project through the menu or is it just when using the project manager?

**Comment by sentience** [comment]
I’m having the same issue; it seems unrelated to the Project Manager package. Symbols fail to load when Atom is launched from Finder (as opposed to from the Terminal prompt), regardless of whether Project Manager is installed or not.
