### ISSUE TITLE
Project root config not overriding projects setting or global setting

### ISSUE THREAD

**Issue by michaelbragg** [danielbrodin/atom-project-manager#298]
I am trying to override the global settings for my local project. Mainly the executable path and config files for my linters. I've created a simplified test with the invisible characters option to show the issue.

### Expected behaviour

Invisible character should be shown.

Settings added to a `~/Sites/test-project/project.cson` file, in the root of a project, to override or be appended to the settings in `~/.atom/projects.[computername].cson`.
In-turn overriding the global settings in `~/.atom/config.cson`.
Only for the project currently open in a window.

### Actual behaviour

Invisible characters are not visible. 

### Steps to reproduce the behaviour

1. **Install** atom-project-manager via package manager GUI.
2. **Set** global setting to enable the showing of invisible characters.
3. **Open** `~/Sites/test-project/` in Atom.
4. **Save Project**.
```cson
[
  {
    title: "test-project"
    paths: [
      "~/Sites/test-project"
    ]
    settings:
     'editor.showInvisibles': false
  }
]
```
5. **Create**  `~/Sites/test-project/project.cson`
6. **Add settings**
```cson
title: "test-project"
  settings:
    'editor.showInvisibles': true
```
7. **Restart** Atom and **Open** test project.

***
Operating System: OS 10.12.1
Atom Version: 1.12.6
Project Manager Version: 3.3.3

**Comment by ryanjbonnell** [comment]
I can confirm this behavior of [per-project settings][1] not working, with or without the [array notation][2].

I'm running Atom 1.12.9, Project Manager 3.3.3 on macOS 10.12.2 "Sierra".

[1]: https://github.com/danielbrodin/atom-project-manager/issues/290
[2]: https://github.com/danielbrodin/atom-project-manager/issues/265

**Comment by mpenna** [comment]
I can also confirm that this is not working. I have tried both ways:

- using per-project settings objects inside the "projects.cson" file under my user's ".atom" folder
- using a "project.cson" file at the root of each project folder

I'm mainly trying to change file encodings between projects, At first, it appears that the per-project settings do indeed take precedence over the global ones, but it seems that by just opening a project with a non-default encoding (anything other than UTF-8) it ends up being written to the global file (.atom/config.cson). Then, as soon as we open another project, one with a different file encoding than the previous one, what apparently happens is that the one that had been written to the global file ends up taking precedence. 

It's a bit confusing, I know... quite hard to trace the whole thing not to mention explain it... feels rather like a wild-goose chase. 

Atom: 1.15.0-beta4 x64
Project Manager: 3.3.3
Windows: 8.1 x64
