### ISSUE TITLE
ability to rename broken project link shown in 'list project' panel

### ISSUE THREAD

**Issue by AndreGeng** [danielbrodin/atom-project-manager#299]
![image](https://cloud.githubusercontent.com/assets/3634890/20911369/6dc97d6e-bba2-11e6-9844-5b3ed20a66e0.png)
I renamed my project on disk, but when I open the 'list project' panel the previous project name is still there but with a broken link, I was wonder if there is a way to remove this broken link

**Comment by michaelbragg** [comment]
`Cmd/Ctrl+Shift +P` > Project Manager: Edit Projects lets you edit the `projects.cson` file storing these settings.

Here you should be able to remove the entry (from `{` to `}`) or adjust the path value to reflect your projects new name.

**Comment by AndreGeng** [comment]
ah, after edited the projects.cson `file,` seems a restarted is needed. Now it's gone. thanks
