### ISSUE TITLE
FEATURE: Sidebar Project List

### ISSUE THREAD

**Issue by timothymarois** [danielbrodin/atom-project-manager#300]
Probably been discussed already, but having the project list in sidebar would be incredible help. At least offer this option in the settings. 

As seen in this example, 

![atom-projects](https://cloud.githubusercontent.com/assets/2489333/20952458/805ffad6-bbfa-11e6-9e25-de50cee9337b.png)

**Comment by danielbrodin** [comment]
This could be a nice feature, but probably not something I will implement myself. A PR would be welcome though if you want to have a go at it?
