### ISSUE TITLE
Suggestion: Settings preview of list item

### ISSUE THREAD

**Issue by lylemoffitt** [danielbrodin/atom-project-manager#305]
It would be really helpful if when editing a project's settings you provided a preview of what the list item would look like. This particularly helpful for the icon choice. I don't know all the icons by exact name. It would be helpful if I could tell when I go the name right. 

Moreover an icon selector (instead of a text field) would be much appreciated. I would populate the list with the file-icons displayed in the tree view. or just a list of all of them. Though, this isn't really a "must have" as, short term, just doing the above would be help enough.

**Comment by danielbrodin** [comment]
I agree, it would be really nice to have. A PR for this would be very much welcome :)

**Comment by marcofugaro** [comment]
Yes, this is the only issue I'm having with this package
