### ISSUE TITLE
Doesn't open tree view anymore

### ISSUE THREAD

**Issue by adamreisnz** [danielbrodin/atom-project-manager#306]
Since I updated Atom to 1.14 (build from master), opening a project with project manager doesn't show the tree view anymore. This makes it seem like nothing has happened and leaves you wondering what is going on. The project does in fact get opened, but you are still seeing a blank screen without tree view.

Could you please look into this and fix the issue for the latest version of Atom? If this is an issue with the tree view package let me know and I'll post there, but I checked with safe mode and it seemed to work ok and shows up the tree view after opening a folder.

**Comment by mikestopcontinues** [comment]
+1 

Please preserve the tree-opening behavior.

**Comment by danielbrodin** [comment]
I'm running atom beta so will have to wait until 1.14 beta is released before I can have a look at it. My guess though is that it has to do with the tree view or atom. Have you tried opening the projects without the project manager?

**Comment by mikestopcontinues** [comment]
That's a good point! Opening a project folder also doesn't open the tree
view. :/


Mike

**Comment by adamreisnz** [comment]
Actually I tried that (see op) and opening project folder does work. Are
you able to build atom from the master branch and have a quick look? Maybe
some of the tree view api changed.

**Comment by adamreisnz** [comment]
I've done some more testing, it looks like it works in safe mode, but not when out of safe mode. I'll analyse which package is the culprit.

**Comment by danielbrodin** [comment]
Nice that you found the issue :) 1.14 beta was just released so just had the chance to test it.
