### ISSUE TITLE
Feature Req: Remove Project

### ISSUE THREAD

**Issue by pingshunhuangalex** [danielbrodin/atom-project-manager#311]
I can't seem to find an option to remove project from the list. Every time I have to use `Edit Projects` to open up the `.cson` file and delete the project object manually... The worse thing is the change won't be reflected immediately, the deleted project will still be on the list if we use `List Projects`. I need to restart atom to let it take effect. Too painful...

Also, I still have no idea what `Update Project` does. No matter how hard I click it, nothing happens...

**Comment by galoat** [comment]
+1

**Comment by NeodarZ** [comment]
+2

**Comment by danielbrodin** [comment]
Yes, this is something that is needed. i'm up for suggestions about how to implement it.

**Comment by patleeman** [comment]
Intuitively, I tried two things to delete a project:

1. Hitting the delete key while the project was highlighted in the project list
2. Editing a project and looking for a delete button.

I think if both are implemented, it would work!

Thanks for the cool extension @danielbrodin

**Comment by stuffnbotany** [comment]
Indeed it would be neat

**Comment by egomadking** [comment]
+4

**Comment by hegoku** [comment]
+5

**Comment by waldnzwrld** [comment]
+ :100:
