### ISSUE TITLE
Support path globbing

### ISSUE THREAD

**Issue by baelter** [danielbrodin/atom-project-manager#314]
Would be nice to be able to add  `~/Users/me/code/prefix-*` and `~/Users/me/code/my_project/*`

**Comment by danielbrodin** [comment]
What is it you want the support for? The issue isn't very clear ;)

**Comment by baelter** [comment]
To define a project to include all folders match a glob

**Comment by danielbrodin** [comment]
If someone is up to adding the functionality for it and send a PR I could add it.
