### ISSUE TITLE
Error when listing projects

### ISSUE THREAD

**Issue by suprko** [danielbrodin/atom-project-manager#322]
Whether I press Alt+Shift+P, or Ctrl+Shift+P then List Projects, I get an error that says "EACCES: permission denied". This has only started happening since I started using Atom 1.15.0

**Comment by danielbrodin** [comment]
Sounds like something have happened to the permissions of the `projects.cson` file. Have you looked at the permissions to see if there is something weird with it?

**Comment by suprko** [comment]
This thing resolved itself somehow, not sure why! In any case it seems that it wasn't a problem with the plugin.
