### ISSUE TITLE
Feature Req: Open Project via Command Line parameter

### ISSUE THREAD

**Issue by dynobo** [danielbrodin/atom-project-manager#324]
Hi, it would be great, if I could open a certain project by providing the projects name as a command line parameter to the atom executable. My use-case is, that I want to have Desktop-shortcuts to a few projects which I use most. Is this possible?

Thanks for your work!

**Comment by danielbrodin** [comment]
I have looked at this before and I couldn't find a solution then. The best solution would probably be to create a custom shell script that does it.

**Comment by dynobo** [comment]
@danielbrodin: Any idea how such a script could look like? How could I control Atom extensions via command line?

**Comment by danielbrodin** [comment]
Not sure if it would be a good idea, but I guess one could create a node script that would require `.atom/packages/project-manager/lib/stores/FileStore.js` to get all projects, and then run `atom project.path[0]`. The FileStore depends on some atom methods though, so one would have to create a global `atom` object containing `getConfigDirPath()`, `config.get()` and `notifications.addError()`.

There is a setting for using environment specific projects though that I guess wouldn't work unless there is a way to read atom settings outside of atom.
