### ISSUE TITLE
Set project specific PHPMD Linter settings

### ISSUE THREAD

**Issue by tillkruss** [danielbrodin/atom-project-manager#325]
I'm trying to use the default `linter-phpmd` setting on all projects and set specific settings for a single project. Is that possible?

I tried this config, but it just sets "phpmd.xml" for all projects. The maintainer of `linter-phpmd` could help my any further: https://github.com/AtomLinter/linter-phpmd/issues/106

```cson
{
  title: "project title"
  group: "group name"
  paths: [
    "/path/to/project"
  ]
  settings:
    "linter-phpmd.rulesets": "phpmd.xml"
}
```

**Comment by danielbrodin** [comment]
There are some issues with the settings in that there seems to be no way to keep settings from being saved globally once settings are saved, and some settings doesn't seem to trigger changes to a package. Not sure how to solve this without native support for projects specific settings :/
