### ISSUE TITLE
Killing performance of CMD + P panel

### ISSUE THREAD

**Issue by ctrlplusb** [danielbrodin/atom-project-manager#327]
Hi, not sure why or how, but when I try to use the CMD + P panel to quick browse to a file my Atom editor grinds to a halt and takes ages to respond.  I need to close the panel to restore performance.  Took me ages to find out why.  Safe mode revealed things worked normally, so I disabled all plugins and added them one by one until I found the culprit.  Turns out the moment I add this plugin the issue occurs.

project-manager 3.3.4
Atom 1.16.0 x64
OS X 10.12.3

**Comment by artarf** [comment]
I had similar problem. When project-manager was enabled atom startup performance was terrible.

Resolved it by disabling `Include Git Repositories` in project-manager settings.

**Comment by danielbrodin** [comment]
Yeah, it could be the search for git repositories if you have many, but there is nothing that should affect cmd+p directly.

The git repositories search could be delayed until the projects list is viewed to fix the performance. Will take a look at it as soon as I have the time for it.
