### ISSUE TITLE
set environment variable when opening project

### ISSUE THREAD

**Issue by scippio** [danielbrodin/atom-project-manager#328]
It will be nice to have this feature (in title).

**Comment by danielbrodin** [comment]
What environment variable is it that you mean?

**Comment by scippio** [comment]
https://en.wikipedia.org/wiki/Environment_variable

**Comment by danielbrodin** [comment]
If you can find a way to tell Atom that I am all up for adding it :)

**Comment by scippio** [comment]
I think we can be inspired from here: https://atom.io/packages/atomenv
