### ISSUE TITLE
Remove old projects after moving project directories

### ISSUE THREAD

**Issue by Tanmccuin** [danielbrodin/atom-project-manager#329]
I had all of my project directories based out of a root folder /clients/ - i recently moved them into a new folder, lets say /new-clients/ - predictably, when opening the Projects browser, i'm getting a path not available for everything. However even if edit the config and change the path to reflect the new path - I'm still getting the path not available warning.

Is there a command to clear out all the existing projects? Or what would be the next best step to clean this up?

**Comment by danielbrodin** [comment]
Have you tried reloading atom?

**Comment by Tanmccuin** [comment]
I have - I made sure before reloading that projectHome is set to /new-clients/ - but on reboot all projects are still listed as "Path not available".  Is it a matter of deleting the plugin and reinstalling? Just curious where this data is stored - I'm fine with removing the project list and starting fresh, i just don't want 30+ broken projects crowding around my working projects.

**Comment by danielbrodin** [comment]
There is a `Project Manager: Edit Projects` command that will show you all saved projects. My guess is that you have saved your projects there.

**Comment by Tanmccuin** [comment]
Ah! That did the trick - just did a quick find and replace there and reloaded Atom. Thanks!
