### ISSUE TITLE
fetchLocalSettings is never called to load local `project.cson`

### ISSUE THREAD

**Issue by brianmhunt** [danielbrodin/atom-project-manager#330]
I have a pretty straightforward `project.cson` in the root of a project, with e.g.

```cson
{
  settings:
    "*":
      core:
        themes: [
          "atom-light"
          "atom-light-syntax"
        ]
}
```

but the settings (and variantions of it that should work) is never added to the project settings.

Looking through the code it appears that the project should be loaded from the `fetchLocalSettings` function in `lib/models/Project.js`, but when I added some debugging it was never called.

It's possible I'm quite confused on how to use it, but I never saw any reference to `fetchLocalSettings` anywhere else in the `project-manager` (or anywhere else in the Atom code base, that I saw), so I thought I'd raise the problem here.

:beers: Cheers

**Comment by danielbrodin** [comment]
It currently only looks for local settings if the project is saved (found in the `projects.cson`file), so is that the case?

**Comment by brianmhunt** [comment]
Got it – the project is not in the `projects.cson` file.

For my scenario it would be ideal if `projects.cson` were not needed, but alternatively I think it'd be a worthwhile note this in the README.

**Comment by brianmhunt** [comment]
... though even after I have added the project to `projects.cson` it appears `fetchLocalSettings` is never called.

**Comment by brianmhunt** [comment]
How/when does `fetchLocalSettings` get called?

It's weird that it never seems to get called and I can't find any reference to it ... anywhere.

**Comment by danielbrodin** [comment]
Ehmmm, neither can I. Will have a look at it.

**Comment by leods92** [comment]
@danielbrodin I think this is the line that got removed and caused this issue: https://github.com/danielbrodin/atom-project-manager/commit/5aa85309001524abab13e09fbd4a61cc9f0adb8d#diff-04f8f60b0079f6cd99f98cc30de69398L187

**Comment by iliyang** [comment]
Has this issue been addressed? I just tried using a `project.cson` file for my project and Atom doesn't load any settings from it. If I put the settings in the `projects.cson` file, they are loaded.

**Comment by jay-hankins** [comment]
Seeing this as well.
