### ISSUE TITLE
Request/Feature - Possible to have the paths relative to the OS?

### ISSUE THREAD

**Issue by kelserj** [danielbrodin/atom-project-manager#331]
I have projects synced on multiple OS's (documentation mostly) and if the paths kinda followed the keybindings concept:

'.platform-darwin':
 "/Users/me/project1"

'.platform-win32':
"C:\Users\Me\project1"

It would allow the projects.cson to be sync'ed for cross platform support. 

Thanks!

**Comment by danielbrodin** [comment]
There is a setting called `Save Paths Relative To Home` that will save all paths relative to the path set in `Project Home` under the Core setting
