### ISSUE TITLE
Files and folders not showing in tree view after switching a project in 1.17.0-beta

### ISSUE THREAD

**Issue by pingshunhuangalex** [danielbrodin/atom-project-manager#333]
Hi @danielbrodin 
Since 1.17.0 introduced the dock feature and tree view is now integrated into the left dock, it seems to interfere with how `atom-project-manager` behaves.

Now when users switch to a different project (in the same window), the tree view will disappear unless I manually restart Atom, and will happen again if I switch again.

Please fix this issue as it renders this package unusable. Thanks.

**Comment by enoversum** [comment]
@pingshunhuangalex Do you mean that the tree is empty when switching to a different project after starting Atom? That's what's happening in my case, a restart brings back the files in the tree view for me as well :) .

**Comment by pingshunhuangalex** [comment]
@enoversum That's exactly what I mean, and it's driving me crazy now...

**Comment by enoversum** [comment]
@pingshunhuangalex Oh yes, exactly. Maybe you could change the topic of the issue accordingly? 'Files and folders not showing in tree view after switching a project in 1.17.0-beta' or something similar :) ?
Hope there is a fix soon, the new tree view introduced a lot of problems with a variety of packages I use.

**Comment by pingshunhuangalex** [comment]
@enoversum what other packages do you have problems with? It's the docker thing that is causing the problem. Hopefully, they will all go away when the official version is released.

If you can't wait, you can also use `nuclide` which has its own tree view, i.e. not affected by this new docker feature.

**Comment by enoversum** [comment]
@pingshunhuangalex autohide-tree-view (doesn't do anything), remote-sync (no right-click options in tree view anymore) and tree-view-autoresize (doesn't work). Also, the Atom Material UI Theme made the tree view unscrollable, but that has already been fixed. I may have forgotten some :). I don't really know what the 'docker' feature actually is..

I only code in PHP/HTML/JS/SCSS, so nuclide is probably nothing for me? As for the tree view, it probably won't work with the other packages then?

**Comment by pingshunhuangalex** [comment]
Right, you got a lot of packages directly related to the tree-view package, which I don't. TBH, I'm not sure if this package is maintained anymore... I'm gonna remove this package if it still goes silent for another month.

Docks are new features which allow routine things to be contained in dedicated space, and can expand/collapse whenever users want to. For now, I know tree-view is in left dock, and linter is in bottom dock by default.

**Comment by enoversum** [comment]
@pingshunhuangalex Oh, okay, thanks a lot for explaining! And yes, these packages do rely on the tree view, seems I am better off not using them at the moment, or accept their limitations then :).
Couldn't find nuclide in the packages repository right in Atom, but will see if I can get it to install for a test :).

**Comment by danielbrodin** [comment]
Unfortunately there is no built in support for opening a project in the same window so it is a hack doing it like it is now. Opening in a new window should still work without a problem since then atom is handling it. Opening in the same window is based on the [atom-project-util](https://github.com/mehcode/atom-project-util/) library, so checking out that code would be the first step if you would like to have a go at fixing it :)

**Comment by enoversum** [comment]
@danielbrodin Being able to fix it ourselves probably wouldn't have brought us here reporting and commenting it :)!

**Comment by OmeGak** [comment]
Driving me crazy as well. 😵

**Comment by bboure** [comment]
I have the exact same issue. Probably related to docks.

**Comment by sorinpohontu** [comment]
Same here, Atom has been update to 1.7.0 and same error on switching projects. Is there a "quick-fix" or I should go back to Atom 1.6.0 ?

**Comment by iPherian** [comment]
I would suggest everyone just open in new window, which still works fine. Only thing that doesn't seem to work is opening in same window.

Also I'd just like to say that if per the maintainer the cause of this problem is a library (atom-project-util) then I would suggest you all file bug reports against that library not this package.

**Comment by mehcode** [comment]
This is fixed in #336
