### ISSUE TITLE
File tree empty when switching projects

### ISSUE THREAD

**Issue by mediapathic** [danielbrodin/atom-project-manager#335]
When I switch to a project via the command palette, the files I had open are reopened as expected, but the file tree is completely empty. If I switch project using the File menu, everything appears as normal, with a file tree. Also the ctrl-cmd-p hotkey does not bring up the project list, I have to do it via the atom command palette (which is probably a separate issue, but I include the information in case it's relevant) 

OSX 10.12, Atom 1.17.0

Thanks!

Addendum: this is only the case when opening in same window, either when that is set in settings, or when using shift-enter on the palette.

**Comment by Yajo** [comment]
I'm affected too. It can be interesting that if I click on the empty project file tree, I get an error that leads me to https://github.com/atom/atom/issues/13410. It seems like [Atom 1.17 changed the panels a lot](http://blog.atom.io/2017/05/16/atom-1-17.html), not sure if it is now Atom's problem or atom-project-manager's. It yields this debug info:


**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: "Fedora release
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At /usr/share/atom/resources/app/src/pane-container.js:253

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (/usr/share/atom/resources/app/src/pane-container.js:253:1)
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app/src/pane.js:875:1)
    at Pane.module.exports.Pane.focus (/usr/share/atom/resources/app/src/pane.js:269:1)
    at atom-pane.<anonymous> (/usr/share/atom/resources/app/src/pane-element.js:51:25)
```

### Commands

```
     -3:20.1.0 intentions:highlight (input.hidden-input)
     -3:19.9.0 project-plus:toggle-project-finder (input.hidden-input)
     -3:18.1.0 core:confirm (input.hidden-input)
     -2:45.3.0 pane:close (div.item-views)
     -2:38.8.0 intentions:highlight (input.hidden-input)
  3x -2:38.3.0 tree-view:reveal-active-file (input.hidden-input)
     -2:37.1.0 intentions:highlight (input.hidden-input)
  2x -2:36.8.0 editor:scroll-to-cursor (input.hidden-input)
  2x -2:35.9.0 intentions:highlight (input.hidden-input)
  2x -2:33.1.0 tree-view:toggle (input.hidden-input)
     -2:31.8.0 intentions:highlight (input.hidden-input)
  2x -2:31.7.0 tree-view:toggle (input.hidden-input)
     -2:27.9.0 fuzzy-finder:toggle-file-finder (atom-pane.pane)
     -2:19.8.0 core:confirm (input.hidden-input)
     -2:16.9.0 sort-lines:sort (atom-pane.pane)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-hg 2.0.14 
atom-jinja2 0.6.0 
atom-material-ui 2.0.3 
autocomplete-python 1.8.63 
bug-report 0.7.1 
busy-signal 1.4.1 
editorconfig 2.2.2 
git-plus 7.9.2 
gtk-dark-theme 0.1.4 
highlight-selected 0.13.1 
intentions 1.1.2 
language-docker 1.1.7 
language-fish-shell 1.0.5 
language-ini 1.19.0 
language-restructuredtext 1.1.0 
language-rpm-spec 0.15.0 
linter 2.1.4 
linter-docker 0.2.0 
linter-eslint 8.1.7 
linter-flake8 2.2.1 
linter-less 2.6.0 
linter-php 1.3.2 
linter-pycodestyle 2.0.2 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.0 
linter-xmllint 1.4.2 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.4.0 
odoo-snippets 0.3.0 
platformio-ide-terminal 2.5.1 
project-plus 0.9.0 
quick-highlight 0.10.0 
rst-preview-pandoc 0.1.12 
sort-lines 0.14.0 
sync-settings 0.8.1 
tablr 1.8.3 
```

**Comment by tanotify** [comment]
+1
I also have the same issue

**Comment by vollyimnetz** [comment]
I experienced the same issue. Trying to switch with "SHIFT + ENTER". The Tree-View is empty.
I also noticed that the path in the Applications-Title-Bar do not change to the new project, even the new "View" seems to have loaded.

---------
Win 10

angularjs@0.4.0
atom-autocomplete-php@0.22.2 (INACTIVE)
atom-beautify@0.29.24
atom-typescript@11.0.3 (INACTIVE)
busy-signal@1.4.1
color-picker@2.2.5
docblockr@0.10.3
editorconfig@2.2.2
file-icons@2.1.6
git-plus@7.9.2
increment-me@0.4.1
intentions@1.1.2
language-blade@0.30.0
language-vue@0.21.2
less-than-slash@0.16.0
linter@2.1.4
linter-eslint@8.2.0
linter-jshint@3.1.2
linter-jsonlint@1.3.0
linter-php@1.3.2
linter-ui-default@1.6.0
minimap@4.28.2
monokai@0.24.0
open_in_cmder@0.1.0
project-manager@3.3.4
termination@0.5.1
tree-view-filter@0.4.6 (INACTIVE)

**Comment by tanotify** [comment]
Issue doesn't connect with Atom and Atom project manager package directly. It's all about atom-project-util - https://github.com/mehcode/atom-project-util/issues/2.

**Comment by tanotify** [comment]
Timeless solution is https://github.com/xream/atom-project-neue

**Comment by schultzern** [comment]
1+ 
CentOS 7.2, Atom 1.17.0 x64 and 1.18 beta

**Comment by SecondeJK** [comment]
+1, MacOS 10.11.16, Atom 1.17.0 x64

**Comment by donald-john** [comment]
+1, MacOS 10.12, Atom 1.17.0 x64

FWIW, changing project-plus to open projects in a new window gets around the issue. I'll be using this in the meantime.

![screen shot 2017-05-24 at 9 20 32 am](https://cloud.githubusercontent.com/assets/7981518/26405191/9021eadc-4062-11e7-92a3-ee2dc743d7b3.png)

**Comment by robhuska** [comment]
I too have this issue. I believe it is something to do with the Atom 1.17 update. This update did some major sidebar/treeview changes (also effecting other packages like Remote-FTP).

**Comment by gsmetal** [comment]
Same issue. And after window reload it returns to previous project.

**Comment by bbodine1** [comment]
@donald-john mentioned above a different package he is using but this project has the same option. Just need to uncheck the `Always Open In Same Window` option in the "Project-manager" settings.

<img width="845" alt="settings_ ___sites_aa_darts" src="https://cloud.githubusercontent.com/assets/2924609/26453359/0793a986-4129-11e7-8228-c1f104185a68.png">

**Comment by robhuska** [comment]
@bbodine1 Yea that is an "ok" work around for now since technically that is what I have to do manually until the package is fixed. But now I am curious as to what package @donald-john is using for project management. I didn't even notice until you mentioned it. I have had other issues with ths package in the past, mainly when using my laptop at work/home, my projects.cson file tends to create a new file when I am on a different network... So I would be ok with trying out a new package for managing projects.

**Comment by donald-john** [comment]
@robhuska https://atom.io/packages/project-plus - give it a whirl! It's been working well for me till this recent hiccup.

**Comment by diminutivesloop** [comment]
@robhuska @donald-john Looks like project-plus may soon be deprecated in favor of project-manager: https://github.com/mehcode/atom-project-plus/issues/95

**Comment by luminairre** [comment]
+1, MacOS 10.12.5, Atom 1.18.0-beta2

**Comment by danielbrodin** [comment]
As some others have mentioned a workaround is to open a project in a new window until https://github.com/mehcode/atom-project-util/issues/2 is fixed. I haven't had time to have a look at it myself, but I would encourage anyone that feels like it to have a look at atom-project-util and see if you can help.

**Comment by pistou** [comment]
+1, Windows 10 (Creators Update), Atom 1.17.2

**Comment by mlaxwong** [comment]
Same issue

**Comment by mehcode** [comment]
:tada: https://github.com/danielbrodin/atom-project-manager/pull/336

–

Thanks for the peer pressure to get it fixed guys. Haha.

**Comment by danielbrodin** [comment]
A release have been made so hopefully it will be fixed :)

**Comment by ryanaltvater** [comment]
@danielbrodin so now I'm getting a new issue, and unsure whether it's related to this or Pigments. When I open a project within the same window and switch between projects, I get this popup...

![screen shot 2017-06-14 at 11 26 46 am](https://user-images.githubusercontent.com/1336787/27140917-c1ab1018-50f4-11e7-9df3-7a739eabc971.png)

When I `shift+enter` and open a project in a new window, it doesn't occur. Again, I'm not sure if this is related to Project Manager or not by firing something on the backend which is causing the notification to fire, but I'll also post this on the Pigments GitHub as well. Any help regardless of who or plugin would be much appreciated. :)

**Comment by fbossy** [comment]
Atom 1.17.2 ia32
Project Manager 3.3.5

Still got the issue with the tree when switching project.

**Comment by bbodine1** [comment]
@fbossy I have the same versions installed and not having any issues. I'd recommend removing Project Manage and re-installing to see if that fixes your problem.

**Comment by bbodine1** [comment]
@ryanaltvater I'm not having the issue. I looked in the settings and see where Pigments has an option to disable reload notifications. Mine was off. 
<img width="764" alt="settings_ ___sites_personal_bradbodine_com" src="https://user-images.githubusercontent.com/2924609/27180014-e5747000-5196-11e7-86c6-31d345a764b0.png">

**Comment by ryanaltvater** [comment]
Hmm okay interesting. That's most likely the case then. I should've checked that I guess, but I've never seen any options for notifications in any of the packages I use lol. I also never saw those notifications before updating PM as well. I'll check it out and report back. Thank you!

Ryan

**Comment by bbodine1** [comment]
@ryanaltvater Atom's latest update changed the way some things work when switching projects causing the atom to reload itself during each switch. That's why Pigments is throwing the notification. It is now getting reloaded as well. 
https://github.com/mehcode/atom-project-util/issues/2#issuecomment-304359605

**Comment by ryanaltvater** [comment]
Gotcha. Well that would make sense then why I'm seeing those notifications, and I can now confirm that checkbox was checked and turning it off fixed the issue. Thanks again @bbodine1 :)

**Comment by fbossy** [comment]
@bbodine1 I'll try removing and re-installing.
