### ISSUE TITLE
Deleting a project from projects.cson does not remove it from "List projects"

### ISSUE THREAD

**Issue by ostrokach** [danielbrodin/atom-project-manager#340]
Removing or modifying projects in `projects.cson` does not appear to change anything? 

1. Go to "Packages" -> "Project manager" -> "Edit projects".
2. Delete some project from `projects.cson` and save the file.
3. Go to "Packages" -> "Project manager" -> "List projects"
    - **All the projects are there as before?**

Sorry if this is something very basic, and is a misunderstanding on my part...

----

Linux Mint 18
Atom 1.17.2
Most recent version of Project Manager

**Comment by egomadking** [comment]
@ostrokach I am experiencing the same thing.

**Comment by jcalvillo** [comment]
### Projects vs Git Repo's in **project list**

- Atom -> Settings -> Packages -> project-manager
  - "Include Git Repositories"

If you uncheck it, an empty _projects.cson_ should make for an empty **projects list.**

If you have it checked, all of your git repo's show up in the **project list** (they have a different icon than the project folders).
