### ISSUE TITLE
shortcut to move left/right on opened projects

### ISSUE THREAD

**Issue by damianobarbati** [danielbrodin/atom-project-manager#342]
How can we move left/right when we have multiple projects opened?
Example: I want to move to the package.json in project "Quant01" on the left (without touching the trackpad!)

<img width="1034" alt="screen shot 2017-06-26 at 11 04 28" src="https://user-images.githubusercontent.com/2225869/27532062-420c1644-5a5f-11e7-9b1e-178c552ee842.png">

**Comment by damianobarbati** [comment]
Anybody can help on this? :(

**Comment by danielbrodin** [comment]
That project tab thingie is not something this package is handling. If it's a native atom thing you could perhaps ask in https://discuss.atom.io/
