### ISSUE TITLE
Cannot switch between project on Atom 1.18 

### ISSUE THREAD

**Issue by siddrc** [danielbrodin/atom-project-manager#343]
Hi ,
I have been using your plugin quite merrily, and to be honest its really very simple to use.
But off-late when I try switching between projects, I am facing an issue below is the screen-shot, and the switching fails opening another developer tool window showing the error stack trace.
Also this was'nt happening earlier, and has started happening after the update.
![error](https://user-images.githubusercontent.com/363164/27803628-1093beca-6048-11e7-83e6-b2470d40db58.png)

**Comment by danielbrodin** [comment]
I can't see anything in the error that has anything to do with the package directly. Does it happen when opening a project in the same window or if you open in a new window?

**Comment by siddrc** [comment]
Hi Daniel,
This was happening when I was switching to another project , which would open in a new window,
Also, I had updated my Atom editor and I am on Windows 10 platform.
I started getting this issue after the update to Atom.
