### ISSUE TITLE
Merge forces for a project-manager / project-plus v3

### ISSUE THREAD

**Issue by mehcode** [danielbrodin/atom-project-manager#345]
👋  @danielbrodin 

I've been considering [deprecating project-plus](https://github.com/mehcode/atom-project-plus/issues/95) but I hesitate to when this repository doesn't seem to be actively maintained. Large issues do get taken care of but it's got some decent enhancements as PRs that haven't even had a comment. I totally get it. It's a lot of work to maintain a large, actively used project.

It's also a bit sad that we aren't at the level of VSCode's project manager. 

Which is why I'm suggesting that we make an `atom-project-manager` (or some other name) organization on github and we both develop and maintain a successor to project-manager and project-plus.

This organization would have at least:
 - `project-service` — In charge of handling the _concept_ of projects.
 - `project-manager` — Anything else. Switching. The finder dialog, etc.

Some features that I think we should have (that we don't):
 - Detection (service)
   - VCS — Any Git, SVN, and Mercurial projects in your `Project Home`
   - "Projects" — Any folders with a `project.cson` file should be considered a project
   - History — Any projects you've opened that fall within your `Project Home`
 - Access History — The ability to remember the last time a project was opened. This would allow tabbing through projects as well as sorting them in the finder.

Thoughts @danielbrodin ?

Thinking more about it.. it could make sense to have each thing as its own package (that would make it easy to scope config):
 - `project-plus-service`
 - `project-plus-service-git`
 - `project-plus-service-atom`
 - `project-plus-service-session`
 - `project-plus-finder`
 - `project-plus-tab`
 - `project-plus`

**Comment by danielbrodin** [comment]
Hey,
Yeah, I have had a lot of other things lately so haven't had that much time working on it. Did a rewrite like a year (or more) ago to make it easier for others to help do fixes, but as usual with OS that doesn't happen a lot.

So a merge could probably help out. I think we should keep the project-manager(atom-project-manager) name though and try keep the package since a lot of people are already using the it. Do you know if the package can be kept as it is if I move it to an organization? I mean if it's just to publish an update and everyone gets it?

I really like the idea with different packages. I kinda started this with moving the settings part out to it's own file, but maybe it would be even better to move it to it's own package that the project-manager would use, to make it easier to expand it and actually make it project specific settings without atom messing it up.

**Comment by danielbrodin** [comment]
- `project-settings` - In charge of project specific settings.

**Comment by Gert-dev** [comment]
@danielbrodin Wanted to drop by to answer your question about publishing under an organisation: I've done the same for php-integrator-base around version 1.2.6 (moved it to the php-integrator organization). The only thing I did was update the `repository` URL in the `package.json` file and publish a patch release. I don't recall the need for any special steps.

Also, great to see that you're thinking about merging forces! I'd like to sneak in a reminder [to the posts I wrote regarding managing project settings via an interface and creating new projects based on types/templates, possibly specified by plugin packages](https://github.com/mehcode/atom-project-plus/issues/36#issuecomment-210545956).

It's not something that's very high priority, but something I think should land in the long term if Atom is ever to integrate projects in a user-friendly way like most IDE's do. I believe it will also remain relevant when language servers become mainstream, as this is something that is handled mostly client-side.

**Comment by mehcode** [comment]
@danielbrodin Let's do it. I agree to keeping the project-manager name. Here are some more thoughts.

##### Packages
 - `project` — Strictly the concept of projects and a few services to support that. This defines a service consumer to provide project definitions and a service provider of the collected total of project configurations. Furthermore this package would provide project metadata. Packages could be built off of such metadata such as a package like `atom-build` using it to access launch configurations.

 - `project-manager` — Defines the concept and structure of `project.cson` files. Provides projects with these to the base `project` service. Contains a project finder.

 - `project-settings` — Defines a consumer for `project` and is solely in charge of taking the `settings` key of the project metadata and applying the config when a project is loaded.

 - `project-discover-git` (better name?) — Defines a provider for `project` with all git projects it can find.

 - `project-recent-history` (beter name?) — Defines a provider for `project` with any project that has been opened by Atom.

Many other packages could be built off of such an ecosystem.

---

As for the organization.. any decent ideas on a name?

 - `atom-project` – _Taken_
 - `AtomProject` – _Taken_
 - `atom-project-manager` – _Taken_
 - `project-atom` – _Available_

**Comment by danielbrodin** [comment]
I snatched the `atom-project-manager` organization name in case we agreed on using project manager as a name :) You have an invite to it

**Comment by mehcode** [comment]
@danielbrodin Accepted. 🎉

**Comment by danielbrodin** [comment]
>  The only thing I did was update the repository URL in the package.json file and publish a patch release

Ok, so I guess that means that I can keep the repository where it is for now, and once we have a updated repository I can just do a new release pointing to the new repository and then everyone should receive another update to download the new package? @Gert-dev

**Comment by mehcode** [comment]
@danielbrodin You on Atom's slack?

**Comment by danielbrodin** [comment]
@mehcode I am, but rarely having it open. Going on vacation today so will be away a fair bit the coming weeks, but can probably have a look here at github now and then at least.

**Comment by danielbayley** [comment]
@mehcode @danielbrodin There’s also _[project-ring]_, so it might be worth reaching out to @vellerefond as well. Also _[project-sidebar]_ by @bripkens… and probably [others]!

Hopefully some consolidation can happen in this space, and once there is a definitive repo, I have a bunch of ideas to contribute.

[project-ring]: https://atom.io/packages/project-ring
[project-sidebar]: https://github.com/bripkens/project-sidebar
[others]: https://atom.io/packages/search?q=project
