### ISSUE TITLE
Open in same window remove tab and treeview header

### ISSUE THREAD

**Issue by cahya6d6d6e** [danielbrodin/atom-project-manager#348]
atom: 1.18.0

os:
- windows 8.1 x64
- windows 10 x64

installed package:
- atom-beautify@0.30.3
- atom-trello@0.7.1
- autoclose-html@0.23.0
- busy-signal@1.4.3
- clipboard-plus@0.5.1
- color-picker@2.2.5
- docblockr@0.10.5
- file-icons@2.1.8
- intentions@1.1.2
- linter@2.2.0
- linter-csslint@1.3.4
- linter-jshint@3.1.5
- linter-php@1.3.2
- linter-sass-lint@1.7.4
- linter-tidy@2.3.1
- linter-ui-default@1.6.2
- merge-conflicts@1.4.5
- minimap@4.28.2
- minimap-find-and-replace@4.5.2
- minimap-git-diff@4.3.1
- minimap-linter@2.0.0
- minimap-selection@4.4.0
- monokai@0.24.0
- open-terminal-here@2.3.0
- project-manager@3.3.5
- remote-sync@4.1.5
- rest-client@1.3.1
- semanticolor@3.5.4
- sync-settings@0.8.2

**Comment by mmn6d6d6e** [comment]
![test](https://user-images.githubusercontent.com/19344000/29697942-556b5d20-897c-11e7-8ac6-d988a92a2c25.gif)

**Comment by robhuska** [comment]
This is still an issue n the latest Atom 1.19.4 on macOS 10.12.6. I have to open projects in a new window to make sure everything is left intact. Hope this gets fixed soon, becoming a chore to use sometimes.

**Comment by mmn6d6d6e** [comment]
tabbar seems missing only when opened project doesn't have any opened file.
