### ISSUE TITLE
how to cycle through project list using custom key maps? 

### ISSUE THREAD

**Issue by xh3b4sd** [danielbrodin/atom-project-manager#350]
Rolling with VIM plugins I would like to select projects within the projects list using `j` and `k` instead of arrow down and arrow up. How to do that?

**Comment by Martinsos** [comment]
Hi @xh3b4sd !I am not creator of this repo, but I wanted to do same thing for emacs keybindings. It is not related to atom-project-manager, but still, what did the trick for me was addin this in keymap.cson:
```
"body":
  # Emacs-like movement.
  "ctrl-n": "core:move-down"
  "ctrl-p": "core:move-up"
```
This affects all the lists (like one in the command palette), including also the list in atom-project-manager.
