### ISSUE TITLE
Opening file from Finder opens wrong project

### ISSUE THREAD

**Issue by johnbillion** [danielbrodin/atom-project-manager#358]
I have a project which contains a few other projects within its subdirectories. The main project is at `/project`, and some other projects live at `/project/subproject1` and `/project/subproject2`.

If I double click a file in Finder (in macOS) that's within one of these subdirectories, Atom opens the root project window instead of the correct project for that directory.

I'm not actually sure if this is a problem with Atom, or with Atom Project Manager.

**Comment by danielbrodin** [comment]
Project manager only does things after atom have already opened a project, so I'm pretty sure this would only have to do with atom.
