### ISSUE TITLE
atom.cson

### ISSUE THREAD

**Issue by danielbayley** [danielbrodin/atom-project-manager#360]
Since local `project.cson` is specific to Atom, I wonder if `atom.cson` would be a better fit? Obviously it should be optional at this point, if supported.

**Comment by balderclaassen** [comment]
atom-project.cson would make more sense to me then. I think being a little more specific is preferred in this case. You never know what other atom related files might be added (want to be added) to a repo/project folder. 

As a side note, I don't see the advantage of a local projects.cson file and think a global one does the job just fine. Also I imagine it will be better at having a project, consisting of several repo's that aren't necesarily in the same folder. Which I believe is one of the use cases of a project manager.
