### ISSUE TITLE
Project not opening in same window anymore

### ISSUE THREAD

**Issue by damianobarbati** [danielbrodin/atom-project-manager#361]
Project keeps opening in new window, no matter the settings.
Before they used to open in the same one.
Also, when I open more than a window with project-manager the cmd key stops working in Atom.

I never reported an atom-plugin before: what info should I provide?
Here my atom packages:
```
├── busy-signal@1.4.3
├── docblockr@0.11.0
├── git-history@3.3.0
├── intentions@1.1.5
├── jsx-comment@0.2.0
├── linter@2.2.0
├── linter-eslint@8.2.1
├── linter-stylelint@4.0.1
├── linter-ui-default@1.6.5
├── markdown-pdf@1.5.4
├── markdown-preview-plus@2.4.10
├── minimap-split-diff@0.3.7
├── pdf-view@0.59.0
├── project-manager@3.3.5
└── split-diff@1.4.3
```

**Comment by jwerre** [comment]
I'm having the same issue. New projects used to open in the same window under a new tab now they open in a different window. 

I'm using:
Project Manager 3.3.5
Atom 1.19.2 x64

This may be an issue with Atom itself. Perhaps [this issue](https://github.com/atom/atom/issues/1722) is resurfacing?

**Comment by damianobarbati** [comment]
@danielbrodin may you help us on this?
