### ISSUE TITLE
How does scoped settings work?

### ISSUE THREAD

**Issue by exalted** [danielbrodin/atom-project-manager#366]
The following `projects.cson` doesn't seem to get picked up for `*.js` files. Instead of using desired 4 spaces, the default 2 is used anyway:

```cson
[
  {
    title: "My Project"
    paths: [
      "/Users/exalted/Development/myproject"
    ]
    settings:
      ".source.js":
        editor:
          tabLength: 4
  }
]
```

Any ideas?

**Comment by lucianomlima** [comment]
Try
```
[
  {
    title: "My Project"
    paths: [
      "/Users/exalted/Development/myproject"
    ]
    settings:
      ".source.js":
        "editor.tabLength": 4
  }
]
```

**Comment by azito122** [comment]
I would like to add that I am also unable to get scoped settings to work. This is a real shame -- most projects don't want the same tab settings for ALL languages.

**Comment by exalted** [comment]
@azito122 I realize this doesn't strictly solves the issue with Atom, however I highly suggest you check out [EditorConfig](http://editorconfig.org) which works if you install [editorconfig](https://github.com/sindresorhus/atom-editorconfig#readme) for Atom (i.e.,`apm install editorconfig`).
