### ISSUE TITLE
Absurdly high disk usage on Linux

### ISSUE THREAD

**Issue by matheusgrieger** [danielbrodin/atom-project-manager#367]
If the option "Include Git Repositories" is enabled, apparently this package starts reading recursively all directories inside the Project Home.

This means that if you have around 10 projects (my case), with `node_modules` inside each one of them, whenever I start up Atom my disk usage goes to 100% and I can't use my computer for quite a while.

I'm currently on Ubuntu 16.04, Atom 1.21.0 x64. Just unchecking the option or disabling this package solves my problem, though this needs a proper fix.

Ps.: sorry if this issue has been reported before, I searched for it but couldn't find anything related.

**Comment by Rob-pw** [comment]
I experience something like this, node_modules is ignored both in .gitignore and in my ~/.atom/config.cson file, yet on startup I get 1.2GiB of disk read.

**Comment by matheusgrieger** [comment]
I have moved to VSCode for some time now. And from there I can bring a possible solution to fix this issue, which would be to add an option for the depth of scanning the package should execute.
So it won't go through all `node_modules` folders if you set to a low value like 1 or 2.

**Comment by danielbrodin** [comment]
There is an option called `ignoreDirectories` where you can add directories that you don't want to go through. It is set to ignore node_modules and vendor as default, but perhaps it fails on linux for some reason. I don't have any computer with linux installed so hard to try it.

**Comment by matheusgrieger** [comment]
@danielbrodin I'll leave that up to @Rob-pw to try and test it, as I'm not using Atom anymore. Thanks for answering, though.
