### ISSUE TITLE
switching on same window makes tree view pane empty

### ISSUE THREAD

**Issue by verajosemanuel** [danielbrodin/atom-project-manager#376]
Atom 1.22.1 Windows 10 x64

Steps:

1. Open project
2. List projects and switch to other project in same window
3. Tree View pane is empty. No file is shown

**Comment by cdmackay** [comment]
May not help, but I cannot reproduce on Atom 1.25.0-beta2, MacOS 10.11. Project Manager 3.3.5.

List Project, select project, shift+enter to open in same window. Tree view fine after switch. Same when opening in new window.

**Comment by nick-prat** [comment]
This happens on for me if I switch from a project that uses more than 1 folder. It fails the first time causing the tree view to go empty, and then if I attempt to switch again it works.

Project Manager 3.3.5
Atom 1.26.1
Ubuntu 18.04
