### ISSUE TITLE
Find options disappear after switching projects

### ISSUE THREAD

**Issue by hknoener** [danielbrodin/atom-project-manager#378]
I'm having a hard time using Atom for a couple of weeks now.

Everytime I switch projects, my find menu is reduced to this and shortcuts like cmd+f, cmd+shift+f are completely gone as well:
![screen shot 2018-02-22 at 13 41 55](https://user-images.githubusercontent.com/4529619/36539288-9a41dc60-17d6-11e8-956a-f69d2229c584.png)
I have to close Atom and open again to have access to the whole set of options, like the normal one:
![screen shot 2018-02-22 at 13 42 14](https://user-images.githubusercontent.com/4529619/36539344-cf3953d0-17d6-11e8-98ca-6a263e929e70.png)
![screen shot 2018-02-22 at 13 42 34](https://user-images.githubusercontent.com/4529619/36539345-cf513dce-17d6-11e8-8fd0-9868f30cb21b.png)

I'm using MacOS 10.13.3, Atom 1.24.0 x64 and Project Manager 3.3.5.

**Comment by timo-piirmann** [comment]
Having the same trouble with same stack versions.

It started after updating Atom from 1.23.x --> 1.24.0 so maybe it's a bug in atom not in project manager

**Comment by hknoener** [comment]
@timo-piirmann To be honest, I haven't noticed to which update it was related to, but I can assure that it's not older than 2-3 weeks.
It would be nice to hear from the dev to see what he thinks about it before creating, if necessary, an Atom bug.

**Comment by Fyrts** [comment]
This seems to be the result of https://github.com/mehcode/atom-project-util/issues/5. Updating atom-project-util to 4.2.0 should resolve the issue.

**Comment by cedric-anamorphik** [comment]
Hi, how to update atom-project-util ?
