### ISSUE TITLE
Atom 1.30.0: After project switch, "git" sidebar/tab is blank

### ISSUE THREAD

**Issue by brycefranzen** [danielbrodin/atom-project-manager#388]
When switching projects to a new project in the same window (in Atom 1.30.0 on MacOS High Sierra), the git pane is left blank. It can be restored by reloading that atom instance (view>developer>reload window).

The issue doesn't happen when opening a project in a new window, only when switching within the same window.

**Comment by JestonBlu** [comment]
I can confirm that this also happens on Windows, although I mainly see the issue with the tab disappearing when using the shift-enter shortcut to stay within the same atom instance.

![image](https://user-images.githubusercontent.com/3339909/46550575-19045300-c89b-11e8-8c32-0d4b2488dc56.png)

![image](https://user-images.githubusercontent.com/3339909/46550589-23265180-c89b-11e8-9f30-ff4d17adc8e4.png)

![image](https://user-images.githubusercontent.com/3339909/46550621-39cca880-c89b-11e8-9f37-7a056a90317a.png)
