### ISSUE TITLE
Switching on the same window makes the tab's header disapear

### ISSUE THREAD

**Issue by Donshel** [danielbrodin/atom-project-manager#389]
Switching on the same window (by holding shift) makes the tab's header (with open files' names and toggled windows' names) disapear. It means I am unable to switch between files which is very annoying.

However if I open a project in a new window there isn't any problem.

I run
Windows 10 Pro (Version 1803)
Atom 1.31.2
Project-manager 3.3.6

**Comment by Sebastian69** [comment]
I'm also affected (Xubuntu 16.04.3 LTS, Atom 1.36.0, project-manager 3.3.7).
