### ISSUE TITLE
Switch to another project adds the folder to the current project

### ISSUE THREAD

**Issue by jakubhruby** [danielbrodin/atom-project-manager#393]
Atom 1.36

- Try to switch to another project (to the new window)
- The project root is added as a new project folder to the current project tree instead of opening a new window

**Comment by Zenike** [comment]
Same problem here since the last Atom update (1.36.0 x64)

**Comment by ryanberckmans** [comment]
Yes, since last Atom update am unable to switch projects / open another project. This breaks a big chunk of my daily workflow, would be great to get a fix today.

**Comment by atalargo** [comment]
Same issue for me (MacOS ) since the last update of Atom itself (1.36.0 x64)

**Comment by ryanberckmans** [comment]
Appears fixed by https://github.com/danielbrodin/atom-project-manager/pull/392

**Comment by ryanberckmans** [comment]
Until next release, here is an OSX 1-liner to patch your local Atom with the fix in #392
```
wget https://raw.githubusercontent.com/danielbrodin/atom-project-manager/9ae2e719dc96ac8394313b967a86aef4d8ef5e63/lib/Manager.js -O ~/.atom/packages/project-manager/lib/Manager.js
```

**Comment by flipty** [comment]
@ryanberckmans fix worked.  wget didn't work but manual download and copy did the trick.

**Comment by dpilafian** [comment]
And for convenience, here's the 1-liner if you don't have `wget`:

    curl https://raw.githubusercontent.com/danielbrodin/atom-project-manager/9ae2e719/lib/Manager.js -o ~/.atom/packages/project-manager/lib/Manager.js

**Comment by mansona** [comment]
This has been fixed 👍
