### ISSUE TITLE
Switching to another project in the same window eats memory

### ISSUE THREAD

**Issue by jakubhruby** [danielbrodin/atom-project-manager#394]
Atom 1.36 (even older ones)
- Switch to another project in same window multiple times
- Keep your eye on RAM usage
- it grows with every switch until the editor stops working

**Comment by jakubhruby** [comment]
![Peek 2019-04-12 08-37](https://user-images.githubusercontent.com/8798755/56017107-94d5d100-5cfe-11e9-9ffa-331820a05f5a.gif)

**Comment by slnt** [comment]
Yeah I think this issue just crashed my editor. 😬
