### ISSUE TITLE
tab bar missing in new projects

### ISSUE THREAD

**Issue by xh3b4sd** [danielbrodin/atom-project-manager#401]
When I add new projects the tab bar is missing. The same behaviour can be reproduced when starting atom like `atom --clear-window-state`. The issue appears to be independent from UI and Syntax themes. When I start a blank atom it looks like this. Any hint on making the experience using project manager more seamless would be highly appreciated. I use it every day and love it. Thanks a lot for all the efforts. 

<img width="1920" alt="Screenshot 2020-05-17 at 15 46 22" src="https://user-images.githubusercontent.com/552769/82148934-9a80dd00-9855-11ea-9b1d-ac673bc2ece0.png">

Jumping to some project the tab bar is missing. 

<img width="1920" alt="Screenshot 2020-05-17 at 15 43 17" src="https://user-images.githubusercontent.com/552769/82148914-673e4e00-9855-11ea-8e39-ded8ec1a73c9.png">

No tabs are visible when I open a file. 

<img width="1920" alt="Screenshot 2020-05-17 at 15 43 43" src="https://user-images.githubusercontent.com/552769/82148964-c8feb800-9855-11ea-8fd0-0d62584ab035.png">

Jumping to another project and back to the previous one shows the tab bar. 

<img width="1920" alt="Screenshot 2020-05-17 at 15 43 59" src="https://user-images.githubusercontent.com/552769/82148953-bb493280-9855-11ea-80ba-e94408794373.png">

---

```
$ atom --version
Atom    : 1.46.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
$ master apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.46.0
python 2.7.15
git 2.14.1
```

```
$ apm ls | grep project-manager
├── project-manager@3.3.8
```

**Comment by Sebastian69** [comment]
Same problem, same atom + project-manager version.
