### ISSUE TITLE
Joining atom-community

### ISSUE THREAD

**Issue by aminya** [danielbrodin/atom-project-manager#404]
Thank you for this great project. We are interested to maintain this package. Would you like to join @atom-community with this package?

@danielbrodin

**Comment by aminya** [comment]
@danielbrodin

**Comment by KevinSjoberg** [comment]
@danielbrodin are you still interested in maintaining this?

**Comment by aminya** [comment]
It seems @danielbrodin has left GitHub. I will make sure to deprecate this package in atom.io/packages and transfer the name to someone else.

**Comment by danielbrodin** [comment]
Hi, so sorry for not responding. I sure am using github, I just don't look at the notifications, so thats why I missed it.
I haven't used atom for years, so it could be an interesting idea. What would it mean to join the @atom-ide-community with the package?

**Comment by aminya** [comment]
@danielbrodin I have sent you an invitation to join the organization. Thank you!
