### ISSUE TITLE
integration with tmux sessions

### ISSUE THREAD

**Issue by MareoRaft** [danielbrodin/atom-project-manager#407]
I typically have 1 tmux session per project that I'm working on, and when I switch between projects I also have to switch between tmux sessions.

Do you think some sort of integration with session switching is a good idea for atom-project-manager?  Do you have any recommendations or ideas for how this sort of feature might be achieved?

(Also, thanks for the awesome package! 😝)

**Comment by MareoRaft** [comment]
I think it would be very useful if each project had its own separate tmux session.

**Comment by danielbrodin** [comment]
I haven't used tmux so can't help you there. My guess is that it would work if you open the projects in a new window instead of the same one?

**Comment by MareoRaft** [comment]
At first glance, that solution appears to work, as far as having a separate terminal session for each project goes.

It is not tmux integration but it is something.
