### ISSUE TITLE
Tab Bar Is Missing

### ISSUE THREAD

**Issue by iamsenthilprabu** [danielbrodin/atom-project-manager#410]
I have two different projects. Tab bar is visible for one project. But when I switch to another project. The Tab bar is missing. All the files are opening in the same tab. 

<img width="1440" alt="Screen Shot 2021-05-17 at 11 40 28 AM" src="https://user-images.githubusercontent.com/4610930/118517261-0fa31e80-b705-11eb-93a6-e6f01b30699a.png">
<img width="1440" alt="Screen Shot 2021-05-17 at 11 42 05 AM" src="https://user-images.githubusercontent.com/4610930/118517264-0fa31e80-b705-11eb-9ccd-2030465c9af9.png">

**Comment by sebastian-65** [comment]
I can confirm (Atom 1.57.0, project-manager 3.3.8, electron 12.0.9-1). Truly annoying issue.

**Comment by danielbrodin** [comment]
Do you open the project in the same window? In that case there is a lib used for that ([atom-project-util](https://github.com/mehcode/atom-project-util)).

**Comment by sebastian-65** [comment]
Oh! @danielbrodin I wasn't aware. Thank you, you've made my day, Sir!

**Comment by iamsenthilprabu** [comment]
yes, If I open the project in the same window, I can see the tab bar. It is missing only if I use a new window.

**Comment by danielbrodin** [comment]
If the problem is when opening the project in a new window, it's probably an atom issue, because nothing is really done except opening the path of the project, and that is done using the atom api.

**Comment by tomcollis** [comment]
I had to disable the built in 'tabs' package and re-enable it and it's been fine since. I expect it started when I was playing with this package and opened a new window.
