### ISSUE TITLE
problem opening from empty window

### ISSUE THREAD

**Issue by mark-hahn** [danielbrodin/atom-project-manager#45]
If I open up atom for the first time with just an Untitled tab and then open a project using the project manager it now opens the project in the same window, which is really cool, except for two problems.

- The project is not in debug mode when debug is is config file
- Only the tree on the left is loaded.  The tabs are not loaded, leaving the Untitled tab only.

**Comment by unional** [comment]
Seems like this is fixed?

**Comment by unional** [comment]
Actually I think this bug still exists, while the atom side bug is closed
