### ISSUE TITLE
Sort project list by recently opened

### ISSUE THREAD

**Issue by olmokramer** [danielbrodin/atom-project-manager#54]
It would be awesome if there was an option to sort the projects by the date the project was opened for the last time. Very useful if you're working on multiple projects at the same time.

**Comment by jpmn** [comment]
I am looking for this feature too.

**Comment by Sciscitator** [comment]
+1
In Sublime I can switch between two projects very easily because the previously chosen project is always preselected. This is the only feature I miss using project-manager!

**Comment by Scotchester** [comment]
Relatedly, I'd also be interested in being able to sort the project list alphabetically.

**Comment by olmokramer** [comment]
@Scotchester That should already be possible, I think you can change ordering from the settings view.

**Comment by Scotchester** [comment]
Wow. I somehow overlooked that. My apologies, and thanks, @olmokramer!

**Comment by slavaGanzin** [comment]
https://github.com/danielbrodin/atom-project-manager/pull/179
