### ISSUE TITLE
shortcut doesn't always work on Windows

### ISSUE THREAD

**Issue by pvradu** [danielbrodin/atom-project-manager#56]
I didn't discover the pattern, but pressing ctrl+alt+shift+p doesn't always work. Tried different combos, like alt+ctrl+shift+p but still doesn't load the menu. From time to time, rarely, the project manager menu  loads just fine. Any debug logging I can enable for you to investigate the issue?

Thanks!

**Comment by danielbrodin** [comment]
This should be fixed in last update
