### ISSUE TITLE
How to set file types to a specific grammar in project settings?

### ISSUE THREAD

**Issue by tsega** [danielbrodin/atom-project-manager#58]
I want to associate all the `.js` files in my project to be opened with a specific grammar settings, and similarly all `.html` files with another specific grammar type. How do I do that? 

Specifically I want:
- `.js` to use [javascript (meteor)](https://atom.io/packages/meteor-api) grammar
- `.html` to use [spacebars](https://atom.io/packages/language-spacebars) grammar

**Comment by guiraldelli** [comment]
Have you tried to use the [file-types](https://atom.io/packages/file-types) plugin and set its parameters inside your project settings?

**Comment by aendrew** [comment]
Apparently file-types is depreciated in favour of `core.customFileTypes`. However, I can't seem to get it to work. Here's my projects.cson:

```
[
  {
    title: "Test Project"
    paths: [
      "/Users/andrew.rininsland/Projects/test-project"
    ],
    settings: {
      core: {
        customFileTypes: {
          'text.html.nunjucks': [
            'html'
          ]
        }
      }
    }
  }
]

```
I'm trying to get all .html files in my project to use the Nunjucks grammar but it's not working. This also doesn't work:

```
[
  {
    title: "France 2017 Poll Tracker"
    paths: [
      "/Users/andrew.rininsland/Projects/france-2017-poll-tracker"
    ],
    settings: {
      '*': {
        core: {
          customFileTypes: {
            'text.html.nunjucks': [
              'html'
            ]
          }
        }
      }
    }
  }
]
```

**Comment by jkroes** [comment]
Is this an issue for anyone else besides myself and @aendrew

**Comment by jonathonoates** [comment]
I'm experiencing this too.
