### ISSUE TITLE
ctrl-alt-shift-p (toggle project) is reserved on windows

### ISSUE THREAD

**Issue by daris** [danielbrodin/atom-project-manager#71]
win32 default keymap:
```
  "atom-workspace atom-text-editor": {
    ...
    "ctrl-alt-shift-p": "editor:log-cursor-scope",
    ...
  }
```

**Comment by Zeex** [comment]
Same on Linux: https://github.com/atom/atom/blob/master/keymaps/linux.cson#L99

**Comment by Zeex** [comment]
Maybe change it to `ctrl-alt-p ctrl-alt-m`?

**Comment by lwblackledge** [comment]
I modified this to "alt-P" (Alt+Shift+P) which does not seem to have any conflicts. You can override this in your custom keymap file:
```
'.platform-win32':
  'alt-P': 'project-manager:toggle'
```

**Comment by danielbrodin** [comment]
alt-p or alt-shift-p feels like a good keybinding if that isn't used. Which one would you prefer as default?

**Comment by lwblackledge** [comment]
I'd vote for alt-shift-P, because by default alt-p brings down the Packages
menu on Windows, in the same way that alt-f brings down the file menu from
the top menu bar.

**Comment by Zeex** [comment]
Updated to 1.15.1 but it's still not working for some reason, although Atom says that alt-shift-P is assigned to project-manager in preferences. Tried asigning to other key combinations like ctrl-alt-m and it worked. It seems like alt-shift-? doesn't work at all...

**Comment by lwblackledge** [comment]
Try alt-P (capital P). Atom seems to be sensitive to casing, and maybe the
shift is inferred?

**Comment by Zeex** [comment]
It seems that was some issue with my system (Ubuntu 14.04). I had Alt+Shift set as the shortcut for switcing keyboard layout, once I changed that alt-shift-p started working in Atom.
