### ISSUE TITLE
Can't save projects

### ISSUE THREAD

**Issue by wpnzach** [danielbrodin/atom-project-manager#75]
I wasn't sure of the proper place to ask for support, so please point me to the right place if this is not it.  I cannot save any projects on Mac OSX.  I get the error below every time, no matter what filename I use:

testproject could not be saved to /Users/support/.atom/projects.cson

Any idea what I may be doing wrong or what I can adjust to get this working?  Thank you!

**Comment by litar1** [comment]
I have the same problem on Ubuntu 14. The error comes from project-manager-view-coffee:93: "Uncaught TypeError: undefined is not a function". A few days ago everything was fine. I removed atom and .atom. I installed a new version prepared for ubuntu. The problem still appears.

**Comment by wpnzach** [comment]
I checked my file permissions and somehow a few folders in .atom were owned by root.  I may have done something as sudo while setting it up and forgotten about it.  I removed Atom and sudo rm -fr my .atom directory.  It appears to be working properly now.

**Comment by danielbrodin** [comment]
Glad it worked out for you :)
