### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by gcornejo** [danielbrodin/atom-project-manager#77]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
atom-workspace.atom.commands.add.project-manager:edit-projects (/Users/admin/Dropbox/Mackup/.atom/packages/project-manager/lib/project-manager.coffee:52:38)
```

**Comment by danielbrodin** [comment]
This should be fixed if you update
