### ISSUE TITLE
Close Project command

### ISSUE THREAD

**Issue by Stephn-R** [danielbrodin/atom-project-manager#79]

**Comment by Stephn-R** [comment]
Should also save the active setup of files

**Comment by danielbrodin** [comment]
Not sure what a close project command would do?

Atom does save the active setup of files, but it's bugged so won't open them if you open the project in an empty(non project) window

**Comment by Stephn-R** [comment]
close project would save the existing file setups and active folders in the sidebar. Then the user could open another project.

**Comment by danielbrodin** [comment]
Ok, well that is built into Atom, but there is however a bug in atom where the project isn't opened correctly in an empty window. If you try to open the project, then open it again it will open in a new window with the active folders and files open.

There is an issue open for it, but I don't think it has been solved yet. I sure hope it will soon.
