### ISSUE TITLE
Sorting by title doesn't sort alphabetically

### ISSUE THREAD

**Issue by olmokramer** [danielbrodin/atom-project-manager#81]
I set the Sort By setting to 'title', expecting projects to be sorted alphabetically, but they get sorted in a random order. I'm on Atom 0.176.0

**Comment by danielbrodin** [comment]
Sorry for taking my time to answer, but does it still do this? Do you have an image of it or could you give me the list of titles to see if it's ordered by anything else?

**Comment by olmokramer** [comment]
It used to be a lot worse... but there's still one package at the top that's not in the right place:
![project-manager](https://cloud.githubusercontent.com/assets/3612514/7732267/ffe7bb5a-ff26-11e4-916d-ab60e96dddf8.png)

Here's the snippet from `projects.cson` that defines the `invisible-borders-roadtrip` entry:
```cson
"invisible-borders-roadtrip":
  "title": "invisible-borders-roadtrip"
  "paths": [
    "/home/olmo/projects/titanium/RoadTripApp"
    "/home/olmo/projects/websites/app.invisible-borders.com"
  ]
```
When I split that one up into two separate entries:
```cson
"invisible-borders-roadtrip-app":
	"title": "invisible-borders-roadtrip-app"
	"paths": [
		"/home/olmo/projects/titanium/RoadTripApp"
	]
"invisible-borders-roadtrip-website":
	"title": "invisible-borders-roadtrip-website"
	"paths": [
	   "/home/olmo/projects/websites/app.invisible-borders.com"
	]
```
it's sorted like this:
![project-manager2](https://cloud.githubusercontent.com/assets/3612514/7732388/f5696092-ff27-11e4-9c49-f63785f1cfeb.png)

**Comment by olmokramer** [comment]
And when I then remove the `invisible-borders-roadtrip-website` entry, the `invisible-borders-roadtrip-app` entry gets sorted at the top. I really wonder how this is happening...

**Comment by olmokramer** [comment]
When I went back to the first situation (with `invisible-borders-roadtrip-*` merged as `invisible-borders-roadtrip` project), and remove the entry for `invisible-borders.com`, the `invisible-borders-roadtrip` entry is sorted in the right spot.

**Comment by olmokramer** [comment]
When I change the `>` in `sortBy` in `project-manager-view.coffee` to a `<`, `invisible-borders-roadtrip` is still sorted at the top, above a project starting with a `y`

**Comment by olmokramer** [comment]
And when I switch the order of `invisible-borders-roadtrip` and `invisible-borders.com` it's the latter that gets sorted at the top of the list. I'll stop spamming you :p it's just so weird...

**Comment by olmokramer** [comment]
Ok, so I removed the `grid.js` entry, and now everything sorts correctly. Then I saved another project, and `invisible-borders.com` appeared at the top again. It seems to be happening when there's more than 10 projects

**Comment by danielbrodin** [comment]
Thanks for looking into this more. Should be fixed in the next release that is coming up in a bit :)

**Comment by olmokramer** [comment]
Yes it seems like it's working now! Thanks :)
