### ISSUE TITLE
Uncaught TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by jptannus** [danielbrodin/atom-project-manager#84]
I can't toggle the Project Manager to select projects. Not from the menu neither from the CTRL + SHIFT + P menu. I always get this error:

Uncaught TypeError: undefined is not a function  /home/{{user}}/.atom/packages/project-manager/lib/project-manager-view.coffee:93

The line in the code is inside the sortBy function:
91|  sortBy: (arr, key) ->
92|    arr.sort (a, b) ->
93|      (a[key] || '\uffff').toUpperCase() > (b[key] || '\uffff').toUpperCase()

**Comment by jptannus** [comment]
But when I run with the console open to pause on exceptions it stops over this line:

@panel ?= atom.workspace.addModalPanel(item: this)

if I look at the atom.workspace methods in this context there is no addModalPanel()

**Comment by jptannus** [comment]
My atom wasn't updating itself ¬¬ sry.

**Comment by Ciantic** [comment]
Huh? Why was this closed? I just got this, and the red bubble by atom had a button to this issue.
