### ISSUE TITLE
Save Project Styling Incorrect/Inconsistent

### ISSUE THREAD

**Issue by stramel** [danielbrodin/atom-project-manager#85]
When saving a project the modal overlay doesn't seem to follow the theme's styles. Is there anyway this could be modified to be styled appropriately using `atom-text-editor.editor.mini` instead of input? Perhaps styled more like the rename of a file?

Love this plugin, but the save project is an eyesore compared to everything else.

**UPDATE:** Doesn't seem too hard, I might submit a PR if I can find time. I was thinking something like this?
https://github.com/atom/tree-view/blob/master/lib/dialog.coffee
https://github.com/atom/tree-view/blob/master/lib/copy-dialog.coffee

**Comment by danielbrodin** [comment]
I have started doing a rewrite of the package that has a style more like the rename modal actually. Not sure when it will be released though, but it will come :)

**Comment by stramel** [comment]
@danielbrodin Great, looking forward to it! :+1:
