### ISSUE TITLE
Multiple root folders are now available in Atom

### ISSUE THREAD

**Issue by Ventajou** [danielbrodin/atom-project-manager#87]
See there:
https://discuss.atom.io/t/multiple-root-folders/15033/5

Can that be supported now?

**Comment by danielbrodin** [comment]
That should already work I believe, but you currently have to manually add the new folders manually in the projects file ´project-manager:edit projects´. Saving a project with multiple folders should work though.

Will see if it can be automatically added though.

**Comment by Ventajou** [comment]
I just tried putting in several paths, and I ended up with several Atom windows. That's on a Windows system if that makes a difference.

**Comment by greenhoe** [comment]
I just tried this out and all my root folders were not saved, I then went into the settings and it showed the paths to all my root folders but still wouldn't open them when I opened the project, it would just open the top once so I added a comma at the end of each root folder and that fixed it.

**Comment by ddliu** [comment]
@danielbrodin 

It's not the default behavior of Atom. 

According to atom/atom#5728, there is a hidden option --multi-folder(enableMultiFolderProject) which is false by default.

> I believe all of your suggestions are implemented in Atom's latest release. The multi-folder support from the CLI is hidden behind an undocumented feature flag: --multi-folder. Once all of Atom's bundled packages are updated to support multiple root folders, this flag will be removed and it's behavior will become the default.
>
>If you're interested, please give atom --multi-folder a try. It'd be great to get your feedback on its behavior early.

**Comment by danielbrodin** [comment]
@ddliu does it work for you with the multi-folder option enabled? Haven't had time to try it out myself.

**Comment by alycda** [comment]
@greenhoe can you show an example of how you **added a comma at the end of each root folder path** ? It sounds like you're saying the comma was placed within the string, instead of delimiting the array of strings. Either way I tried both and neither worked for me.

@danielbrodin I'm on a mac, have multiple folders listed in my 'paths' option, ran atom --multi-folder and I still only see the first folder in my sidebar.

**Comment by alycda** [comment]
UPDATE: My mistake, I ran atom -- multi-folder, then opened the project and I do now see multiple folders in my sidebar, as defined by the .cson config.

However, I would like the option to 'name' each folder. The reason for this is that I do not have control over the folder structure of the project I'm working on, so I can't rename the folders. We have 2 project bases (SVN repos) in which the files I'm working with are in a subfolder (src/main/webapp). 'webapp' isn't very useful (and both repos use this structure), so I'd like to name it something else.

**Comment by petemill** [comment]
Note that it appears you still need to edit your project file and add the comma between the strings in the [] array. This should probably get fixed.

...and also run atom --multi-folder for now.

**Comment by louisgv** [comment]
Tried --multi-folder in windows but seems like it's not working. How does a project get re-opened? I would like to take a look at the issue :-?..

**Comment by danielbrodin** [comment]
This should be fixed now since 0.188.0
`The atom command now opens multiple root folders in a single window when given multiple paths.`
