### ISSUE TITLE
Renaming moves file or folder to another project

### ISSUE THREAD

**Issue by lovebear** [danielbrodin/atom-project-manager#90]
Only have project manager enabled along with the core plugins...

I open 2 projects... On the second project I rename either a file or folder, it moves the file or folder under first project. Not just visually within atom, but actually moves it on the file system.

**Comment by danielbrodin** [comment]
Project Manager doesn't do anything with the files so really don't think it has anything to do with this. Have you tried to disable the package and see if it still happens?

**Comment by eviljoe** [comment]
I recently opened a ticket against tree-view for this issue (atom/tree-view#394).  When I upgraded to the latest version of atom (v0.186.0), it fixed this issue.
