### ISSUE TITLE
First project open opens twice

### ISSUE THREAD

**Issue by MaxGiting** [danielbrodin/atom-project-manager#92]
If I open a fresh Atom on Windows or Mac and then immediately open a project via the project manager. It will open the project, but if I open it again a new atom window will open this time loading all the open files that were open last time I closed atom.

It's as if the first open is not logged in memory and afterwards it is. The first project I open opens the root folder and is the correct project, but I can open that project again.

**Comment by danielbrodin** [comment]
This is a bug in Atom. There is an issue for this but not sure what the status for it is.
