### ISSUE TITLE
Language Specific Project Settings

### ISSUE THREAD

**Issue by arbourd** [danielbrodin/atom-project-manager#94]
Now that Atom [supports scoped settings](http://blog.atom.io/2014/10/31/language-scoped-config.html), any chance that project manager could manipulate them on a per-project basis?

Seemingly `settings` are merged into global, or scoped to the plugin, and do not overwrite globally scoped syntax settings.

**Comment by danielbrodin** [comment]
Yeah this is something that can be added. Just need to find the time to do it :)

**Comment by danielbrodin** [comment]
This have been added in the latest update

**Comment by arbourd** [comment]
Awesome! Thanks @danielbrodin; really appreciate it.

**Comment by benjic** [comment]
:+1:
