### ISSUE TITLE
 Multiple folders.. now you see ‘em now you don’t

### ISSUE THREAD

**Issue by TreyTaylor** [danielbrodin/atom-project-manager#96]
Hey :-)

I downloaded the .zip version of Atom (0.187) and was disheartened when I tried creating and saving projects. Before, on Atom version 0.184, I could add Root folders and save that with Project Manager and when I loaded the projects they would open with both folders in ONE window.

Now, I add the root folders, save with Project Manager etc. but when I load it only loads the first root folder and then it will load the other folders in multiple windows, I checked the projects.cson file and both folder paths are there, it just wont load the same way as 0.184.. anyone else experiencing this?

**Comment by r-owen** [comment]
I am seeing the same problem on MacOS 10.9.5 using Atom 0.187.0 and project-manager 1.15.5. Switching projects results in one window per root folder in the new project.

**Comment by TreyTaylor** [comment]
FOR ANYONE WHO FINDS THIS:

It does work and heres how:

go to 'edit projects' under packages > project manager > edit projects
add 'group':'group-name' to the project config like so:

'atom-project-manager':
  'title': 'atom-project-manager'
  'group':'test'
  'paths': [
    'C:\\Users\\treytaylor\\Documents\\GitHub\\atom-project-manager'
    'C:\\Users\\treytaylor\\Documents\\GitHub'
  ]

and save the config file, then load the project and see for cha self :-)

@r-owen

**Comment by r-owen** [comment]
I tried it and it does not work for me. Adding 'group' did not change anything. I even restarted Atom.

Even if it worked, I find it a puzzling requirement. Why is 'group' needed and what is its value supposed to indicate? Why not just automatically group all paths?

**Comment by TreyTaylor** [comment]
@r-owen ah fair beanios :-)
for me (windows) I had to specify the group, Mac might of had a better upgrade (if that makes sense o.O)

**Comment by danielbrodin** [comment]
Group really shouldn't have anything to do with it, so that it made it work is kinda weird :)
0.188.0 seem to have fixed it though like @r-owen said.
