### ISSUE TITLE
Hide path in .gitignore

### ISSUE THREAD

**Issue by tutuca** [danielbrodin/atom-project-manager#97]
Atom sort of shadow paths on `.gitignore` but I'd like the option to hide them. As in intellij project scope.

**Comment by danielbrodin** [comment]
This is part of the tree-view package in the settings.

**Comment by tutuca** [comment]
No it's not.

**Comment by danielbrodin** [comment]
If you do not mean the "Hide VCS Ignored Files" option I have no idea what you mean.
